### ISSUE TITLE
Saxilby Fragment records

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#106]
There are two records for the Saxilby Fragment:

https://www.diamm.ac.uk/sources/992/
https://www.diamm.ac.uk/sources/378/

The "real" record (378) has significantly less information attached to it than the "pointing" record ("See:"). These records should be normalized, and the pointing record should be removed (refs #85).

**Comment by juliacmcf** [comment]
fixed; pointing record remains (for now)

**Comment by ahankinson** [comment]
This is a duplicate of #85
