### ISSUE TITLE
inventory formatting

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#108]
I'm looking at the inventory for https://www.diamm.ac.uk/sources/2348/
There is a confusion of text colour here, but I'm sure you're on that already.
LH column:
Given that the black is more emphatic than the blue it might be better to have e.g. 'Number of voices...' in blue and the rest in black? Or perhaps remove the bold on Number of voices...

RH column: 
I prefer the black/blue of the RH column (listed by composer), though it might be good to emphasize the composer names with black and the rest in blue (keeping the page numbers in black). The spaces around the colons are inconsistent between the cols -- missing in col. 2; likewise spacing around the hyphen in the page spane (two spaces before and one after in col. 1). Also in this col, the colon disappears when a piece is only on a single page (in the LH col this doesn't happen as single page works have the start and end numbers repeated). I am not sure how other people feel, but I wonder if sorting under each composer by title might be a good idea to enhance the usefulness of that column, rather than listing by folio number under each composer?

There is a listing for John Taverner (in this col.) followed by '(uncertain attributions)'. I would prefer a '/' in brackets, or just 'uncertain'. However, whereas for some pieces the attribution is merely uncertain, in this case the work is ascribed variously to two composers (hence the uncertainty), so in this case the piece should more properly be under a heading that says: 'Taverner, John/Tye, Christopher (uncertain)', although in this case it may be unnecessary to include the word 'uncertain', since that's fairly obvious! I have a nasty feeling that at some point people may want to be able to give one attribution more weight than another, but I don't see that we could do that!

Blank pages are assigned as 'anonymous'. I might need to have a different composerKey for blank pages (people expect to see blank pages listed in an inventory so they know the pages are blank and not missing or omitted from the inventory by accident). This would also remove them from the RH col list (by composer). Let me know what I should do about this in the FM database so that they migrate sensibly.

**Comment by ahankinson** [comment]
New UI for inventories, so this no longer applies.
