### ISSUE TITLE
Buggy Scroll view

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#110]
The view MSS as you scroll feature is still pretty buggy. I'm seeing duplicate records if I scroll too fast, and the 'voices' key displays even if there is no voice information.

It also needs to be made to look better. It still looks like it's half-done.

**Comment by belljustin** [comment]
- The keys only appear if they have content now
- I'm having trouble reproducing the duplicate records issue
- Still working on making it look better...

**Comment by ahankinson** [comment]
Superseded by new view.
