### ISSUE TITLE
Sanity for branch names

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#115]
I'm having problems keeping track of all the different branch names and types, so I will propose that all new feature branches should be prefixed with `feature/` (not `feat` or `refactor`). So 'feature/browse-interface`or`feature/improve-foo`.

**Comment by belljustin** [comment]
Yeah, sorry about that. I was trying out a few different ways to name the branches but your convention is best. Do we have any groupings other than `feature/`?

**Comment by ahankinson** [comment]
Don't think so. Maybe 'hotfix/' but that's not for a while yet.

**Comment by ahankinson** [comment]
Fixed.
