### ISSUE TITLE
Ferrell Vogüé images don't load

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#119]
https://beta.diamm.ac.uk/sources/3774/

Likely a problem with the IIIF manifest generation.

**Comment by belljustin** [comment]
#121 may be related

**Comment by belljustin** [comment]
Looks like the IIIF manifest has an image with width/height = 0. This causes the getMaxZoomLevel method to return a value < 0 which is used and breaks when it tries to create an Array of negative length

**Comment by ahankinson** [comment]
Yes, the problem with this is when there is an image that was referenced but not found on the server. I will look into this later.

**Comment by ahankinson** [comment]
Fixed.
