### ISSUE TITLE
Persons...

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#120]
There are currently overlaps in the persons and scribes, which I think you’re going to resolve? Or should I attempt to merge these into one in the FM database.

I’m thinking particularly of my test search on John Baldwin, which turned up Baldwin, John (Person) and Baldwin of Windsor, John (Person). One is an owner and one is a scribe, not necessarily of the same set(s) of books. It would be preferable if these records were a) reconciled so they both say Baldwin, John, with the fact that he was a singing man in Windsor as (?) an ‘affiliation’, but also that rather than saying 'person' each time we might be more specific and say one is (owner) and one is (copyist). However, I’m not sure if the will be possible. If not, it would be better not to have two entries that say Person, with no indication as to why he turns up twice. This may be addressed by the final migration of data when we eventually dump filemaker.

**Comment by juliacmcf** [comment]
Oh, and it looks as if Baldwin turns up a third time, also designated 'person' but probably in this case as a composer.

**Comment by ahankinson** [comment]
If you can somehow indicate that these are the same people in the Filemaker database, I can resolve these at import. Otherwise we can fix it later in the new website.

**Comment by ahankinson** [comment]
You are now able to merge person records in the admin, so I'm going to close this.
