### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#122]
Not (yet) seeing the login link from the images tab in the source display if I access a source page without being logged in first. When I log into my account from a source page I bounce right back to the home page, so have to go through my search criteria again to get to where I was. I'm sure this is something already on your list (as is a message saying that my login has failed when I put in the wrong details!!).

**Comment by belljustin** [comment]
@ahankinson, did you address this issue with #99

**Comment by ahankinson** [comment]
Yes, this has been addressed but not deployed.
