### ISSUE TITLE
Inverted images list

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#125]
Inverted images that need to be fixed by a new upload:
GB-Llp H5142.P.1545
Caius Choirbook versos

No action required from anyone else, this is just so I can keep track of this particular problem and make sure I don't forget to upload anything in the corrected set.

**Comment by juliacmcf** [comment]
Harley 3109 not loading

**Comment by ahankinson** [comment]
Old issue. Assumed fixed.
