### ISSUE TITLE
Short source description order

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#128]
Example of a search:
https://www.diamm.ac.uk/search/?q=I-PSac+Bibliotheca+musicalis%2C+B.+3.+5
Result:
 I-PSac Bibliotheca musicalis, B. 3. 5 Source
Parchment fragment, 14th - Early 15th century (c.1400) c. 230 x 122, 229 x 162, 231 x 132, and 232 x 152 mm ;orig. c. 250 x 165 mm Archivio Capitolare di Pistoia, Pistoia Inventory contains 2 composers with 9 compositions. Other identifiers: Pist I-PSac5 PistAC 5 Notations: black full mensural coloration in black void

Need to put 'Archivio Capitolare di Pistoia, Pistoia' first, and insert punctuation before 
'Inventory contains' and 'Notations', and between the full version of the library name (when it has been moved to the front of the description), and anything following it. Otherwise it's great!

**Comment by ahankinson** [comment]
I think this has been resolved.
