### ISSUE TITLE
Add feedback form

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#13]
Add a feedback model and form for registered users. Maybe it can be attached to any piece of content by generic foreign key?

**Comment by ariellegoldman** [comment]
Where should the feedback appear? on the website? only visible to admins? or emailed to some account?

**Comment by ahankinson** [comment]
I'm wondering if this is a duplicate of #32. The idea is that users can contribute changes to the records (spelling mistakes, missing information, etc.) I think I should close this issue and you can use #32 as the issue for this.
