### ISSUE TITLE
Remove workaround for Diva not resizing on tab change

### ISSUE THREAD

**Issue by jeromepl** [diamm/diamm#138]
A few weeks ago @belljustin introduced a workaround that involved firing a fake window.resize event to force the Diva instance to adjust to its new size.

I just found that Diva already has an event to handle just that: https://github.com/DDMAL/diva.js/wiki/Integrating-Diva#panel-size-adjustments

Firing the `PanelSizeDidChange` event should thus fix this issue.

**Comment by belljustin** [comment]
:+1:
