### ISSUE TITLE
Duplicate images for MS Add. 17802

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#141]
For source ID 1873 (Gyffard), there are duplicate image entries in the Image table. Additionally, the filenames for the images should be "GB-Lbl_Add17802" (note uppercase A).

**Comment by juliacmcf** [comment]
These have already been identified and removed from the FM database, and the filename is correct in the set of images left in place. It wasn't the only source to have two sets of filenames either!

**Comment by ahankinson** [comment]
👍
