### ISSUE TITLE
Make browsable lists alphabetical

### ISSUE THREAD

**Issue by NBellDiamm** [diamm/diamm#188]
Can the browsable lists in the search screen be sorted alphabetically instead of by ASCII value? The present method makes them case-sensitive so there are two alphabetical series, sometimes with duplication between capitals and lower-case (eg Gothica and gothica in Notation, or Organ book and organ book in Source Types. If these can be interfiled then it would improve searchability.

**Comment by ahankinson** [comment]
The duplicated entries will be sorted out as we go through the data. I believe the idea is that they will be normalized to a specific form, which will take care of the sorting issue. This issue can be used to track progress on this front.
