### ISSUE TITLE
Country searching for GB sigla

### ISSUE THREAD

**Issue by NBellDiamm** [diamm/diamm#189]
At the moment a search in Archive locations brings up 65 for England, 29 for Great Britain, 4 for Scotland and 1 for Wales. Since this is basically a filter connected to the RISM sigla, could they all be merged into Great Britain? It does not work at the moment to have Durham in England but Canterbury in GB, for example. (A problem arises for the one Northern Ireland source, in UK but not GB - but RISM chooses to put these under GB (as GB-BFu)

**Comment by ahankinson** [comment]
At the moment this is very much in flux. We've normalized the data into "Geographic Areas," which can be hierarchically arranged. We may be moving towards the following (e.g.,):

- United Kingdom
  - England
    - Durham
  - Scotland
    - Edinburgh
  - Northern Ireland
    - Belfast

At the moment it's like this, except "Great Britain" is a substitute for "United Kingdom." This is excepting a few cities whose parent hasn't been moved from "Great Britain" to "England". (Canterbury being one). This will be gradually cleaned up in the database.

I would prefer to see the name changed to "United Kingdom", even though the RISM sigla is "GB". There are several examples of this being a common practice; the one that springs to mind first is EU license plates on cars.

@juliacmcf may have different opinions on this, though, so I think it's still an open discussion.

**Comment by ahankinson** [comment]
I should also mention that the "Geographic Areas" are also linked to source provenances and organization locations. So if a source has a provenance of "England" it will be connected to a single "England" database entity as is the parent of "Durham". This will make it possible to see and relate all the records geographically. 

So we will need to have an "England" entity anyway, and it makes sense to incorporate that into the larger 'system' of geographical representations within DIAMM.
