### ISSUE TITLE
Todo: User migration

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#2]
Current users can sign in with their old username or e-mail. If the system detects that they were a former user, it will prompt them to update their password.

Figure out: Can this be generalized for all users (new / existing)

**Comment by ahankinson** [comment]
Update: Users have been migrated with randomized passwords. Returning users should be able to recover their passwords (functionality needed).

**Comment by belljustin** [comment]
Is this superseded by #87?

**Comment by ahankinson** [comment]
No, I can close this. This was just to get the users into the new database.
