### ISSUE TITLE
Blank leaves in inventories

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#208]
If I attempt to add an inventory entry for blank leaves (i.e. to differentiate between missing leaves or a skip in numbering) I get a server error when I try to save. It could be because I'm not filling in a vital field, but it's not clear whether that is the problem, or that the server just doesn't like my item not being linked to a composition (even though it should allow this).

**Comment by ahankinson** [comment]
Could you take a screenshot of the record just before you hit save?

It doesn't need to be attached to a composition, but you should fill in the 'Source Attribution' field with "[Blank leaves]" (or something like that).

**Comment by juliacmcf** [comment]
I suspect it was the Source Attribution field that was the problem then… I’ll give it another try.

**Comment by juliacmcf** [comment]
Still not working. The previous piece I put in was a 'composition' and that's now in the inventory list  (and miraculously in the right order! I don't have access to order numbers if things are displaying wrongly...)
![screen shot 2017-06-09 at 15 45 40](https://user-images.githubusercontent.com/10816169/26980879-545afb3a-4d2b-11e7-928a-874b7de36da6.png)
![screen shot 2017-06-09 at 15 45 49](https://user-images.githubusercontent.com/10816169/26980880-545f1f62-4d2b-11e7-94af-9b0c186e37a7.png)
![screen shot 2017-06-09 at 15 46 02](https://user-images.githubusercontent.com/10816169/26980881-54602466-4d2b-11e7-9d05-dfaec091147f.png)
