### ISSUE TITLE
Folio numbers available in add item...

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#209]
If I accidentally put the wrong folio number in the box of folios assigned to a new item and select-click to remove from the list, it does not reappear in the list of available folios. (I selected a single number by mistake, but didn't want to select further numbers in case they went in the wrong order, so removed the first number, but then couldn't include it in the bunch that I wanted to copy). Not a major issue, and it may of course be intentional!

**Comment by ahankinson** [comment]
I think it's a Django bug. It does re-appear, just at the bottom of the list.
