### ISSUE TITLE
MS listings

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#21]
Any 'short title' list of MSS/hselfmarks should include the tag line following the shelf mark (perhaps in brackets or separated by a dash?); this is in the Source Table field <Tags>, the point being that you don't have to switch to the full MS description to find out what type of source lies behind a shelfmark (e.g. fragment, choirbook, partbook, chant, theory treatise, etc.). The current facet listing was supposed to do this, but the layout meant it was too narrow to accommodate the information.

**Comment by ahankinson** [comment]
Fixed
