### ISSUE TITLE
Sorting for Anonymous Compositions

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#218]
From @juliacmcf 

Here's an oddity: I just searched on Anonymous compositions (BRILLIANTLY USEFUL, THANK YOU! I needed numbers of anyonmous works for statistics) but the resulting order was quite odd: I would have expected an alphabetical result (since there were no other search criteria), but the results were clustered by letter, starting with i and ending apparently with f, plus three out of order pieces tacked on the end. Can't quite see what the order is there, though in this case it's not that important, and presumably if I added a letter or two to the work title that would act as a filter.

**Comment by ahankinson** [comment]
How would you expect it to sort? I've tried in the back-end search interface to sort by 'title', but since some composition titles start with punctuation like "..." it means that they all sort first.

**Comment by juliacmcf** [comment]
That wouldn't be a problem as it just means the beginning of the piece is lopped off. When I just click on 'yes' for anon compositions I get this (screenshot)
![screen shot 2017-06-16 at 15 45 50](https://user-images.githubusercontent.com/10816169/27231649-2ccb7c18-52ab-11e7-8e59-6f41f8fd1dc2.png)

, which appears sorted, but I'm not sure why it starts with 'i'. Could it be sorting as if on a page order, so roman numerals first then arabic? I've also screenshotted the last page...
![screen shot 2017-06-16 at 15 47 44](https://user-images.githubusercontent.com/10816169/27231648-2cbc01b6-52ab-11e7-83f8-9abdbb54a0f9.png)

**Comment by ahankinson** [comment]
Yeah, I don't know why it sorts that way either. I can fix it, I just need to know how you would like it sorted. I can definitely do title.

**Comment by juliacmcf** [comment]
I would go alphabetically by title, even though the first in the list will be … xxx. That doesn’t matter. At least if you know something starts with the letter ’t' you can go to the end of the list and work forwards rather than having to click through page after page in search of the ’t’s, and possibly not find them all together! I can imagine this being useful in identifying fragments where there is only a partial text too.
