### ISSUE TITLE
Inventory image links produce error

### ISSUE THREAD

**Issue by Theodoridis** [diamm/diamm#220]
When following an image link from inventory for [F-CH MS 564 (Chantilly Codex)](https://www.diamm.ac.uk/sources/201/#/inventory), the following error is produced: 

> **Error** Invalid objectData setting. Error code: 404 Not Found

It appears to effect every image link in the inventory.

**Comment by Theodoridis** [comment]
Error has gone but now other issues:
1. Image link icon has disappeared for all items in inventory overview. Image link icon only appears when you expand item details.
2. When you now follow the image link, the image viewer does not load at all. No images can be seen.

**Comment by ahankinson** [comment]
For this particular MSS we don't have the images to show online. (Notice there is no 'image' tab on the top) The icons were showing up because of a couple problems, but they weren't supposed to! I missed the icon when you expand it -- I will have to make that disappear too.
