### ISSUE TITLE
Titles for MSS headings

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#23]
From @mscuthbert:

This reminds me (if you're up for suggestions yet), I think that the heading of a manuscript page / search result should be in the form "Oxford, Bodleian Library, Canon. Misc. 213" and not "GB-Ob Canon. Misc. 213" and only use RISM sigla for linking when space is at a premium; given that we're using post-1980 RISM sigla now ("GB-Ob Canon. Misc 213" instead of "GB-Ob213") the space savings is far less than it used to be, compared to the clarity (and potentially higher Google search results)

**Comment by ahankinson** [comment]
Julia and I talked about this. The main issue seems to be that the library/archive names are not always as nice and succinct as the Oxford ones; consider https://beta.diamm.ac.uk/sources/4037/, which would result in:

Washington, Georgetown University, Special Collections Joseph Mark Lauinger Library, MS 10 (St. Andrews Psalter or Wode Partbooks)

It's not the length that is the problem, though, it's the _variability_ in the length in the archive name. Using the RISM sigla is an easy way to ensure that the formatting of the line doesn't go too squirrely if the archive name gets too long.

That said, it's all very much in flux and I welcome any further suggestions.

**Comment by juliacmcf** [comment]
One criticism that has been made of diamm.ac.uk from the outset is that it's very much designed for people who already know what they're looking at and using -- i.e. medieval musicologists. Not even all musicologists understand RISM sigla, but I was very surprised to learn that library sigla are not universally used in all subjects. So academics from other disciplines are not familiar with RISM sigla, never mind poor Mr Joe Public who wants to make an edition of a piece of music he has heard. So I'm in agreement with Myke that something more friendly to a broader readership would be preferable if it could be made to work.

**Comment by ariellegoldman** [comment]
Andrew and I have discussed this and come up with a suggestion. After looking at the archive names, there are too many that are too long to include the name and the shelf mark. An option would be to list the siglum and shelfmark as the main heading but include the archive name just below it in smaller font. We'll have a prototype of this soon.

**Comment by ahankinson** [comment]
Further to Arielle's message, we've gone through a few iterations and the best seems to be something along these lines:

![etc_demo](https://cloud.githubusercontent.com/assets/163183/15271154/a6048128-1a09-11e6-8fac-456a6a83f1fb.png)

i.e., Using the siglum in the header, but putting the library (and city + country) in very close proximity.

**Comment by juliacmcf** [comment]
Great to see the tags finally being used!
