### ISSUE TITLE
Usability support when adding multiple pages

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#251]
It would be handy if 'save and add another' reiterated the sourceKey in the relevant box, and also the  page type could more usefully default to 'page' rather than ----. Both or either of these would save a lot of time.

**Comment by juliacmcf** [comment]
https://www.dropbox.com/s/ze9ucv3or2p6pg1/movie.mov?dl=0

**Comment by ahankinson** [comment]
The second (pre-select page) is totally possible; The 'sourceKey' issue may not be possible.
