### ISSUE TITLE
Newly added pages don't show up when trying to add items

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#252]
Maybe a cacheing problem?
![screen shot 2017-06-29 at 13 44 33](https://user-images.githubusercontent.com/10816169/27688072-28661f86-5cd1-11e7-921d-2dbb4fa64884.png)

**Comment by ahankinson** [comment]
Did you click 'save and continue editing' after attaching the source? The pages won't show up until after it knows what the source key is, so you need to save the item record first before they will appear.

**Comment by juliacmcf** [comment]
I had saved and exited everything after creating the new pages (I created several pages as we were given an inventory, so I had to make page records first (about 36 of them) then attach items, so each page record was saved as I made it, and I could see it in the page list when I searched on the source they were attached to. I then attempted to attach those new pages to an item, but they weren’t listed in the scrolling list of pages for that source when I went to add an item to the source.

**Comment by ahankinson** [comment]
I tried this again and it worked for me. Are you still seeing the same problem?

**Comment by juliacmcf** [comment]
You’re right, they turn up if you save and continue editing.
