### ISSUE TITLE
Can't search the bibliographies...

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#255]
A passing reference in a commentary to 'Bernstein, Index p. 31' sent me to DIAMM to try and find the book or article it referred to, but I couldn't search either on author names or bibliographical titles (I suppose I could have gone back to the old FM database to find it). I did eventually find a MS with an article by her in it, and by clicking on her name found the other things which led me to the right book, but it was a very long way around. I'm not sure how one might allow users to search on the bibliographies without ending up with a whole mess of stuff in the general search results, but perhaps don't search in the bibliographies under normal rules, but add 'Search authors' to the list on the left? Not much need to search article titles as people would be mostly looking for articles in relation to MSS (I imagine) and that would be covered by going to the MS and looking at the specified bibliography list.

**Comment by ahankinson** [comment]
What if we created another section in the top menu, 'Resources' where the bibliographies, dissertations, and additional sub-sites lived. I don't want to add bibliographies to the 'main' search since I think it would clutter things up quite a bit, but a separate site might be better for that anyway.

**Comment by juliacmcf** [comment]
Yes, it would certainly complicate to add bibliographies to the main search and I agree that that’s not a good option, but if they were searchable somewhere on the site I think it could prove very useful, and might be useful in the future if we added any resources that needed to be searchable.

**Comment by ahankinson** [comment]
As a stop-gap, In the admin interface you can search the bibliography entries by going to the 'Bibliography entries' section. It will search the author last name, title, and abbreviation fields.

**Comment by juliacmcf** [comment]
Thanks!
