### ISSUE TITLE
items that are composers only: a question

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#259]
e.g. sourceKey 2609 (MS 237 (c)).
The list of items for this source have no visible composer names, so if I want to add a piece title and folio number for one of those records it's not possible. Presumably if I find myself in a position to add an inventory to a MS therefore the best way to do it is to delete all these dummy records and start fresh?

**Comment by juliacmcf** [comment]
Actually this has unexpectedly become a problem. One of the composers listed (from CCM) is incorrect: Mr Noe has been turned into Noel Bauldeweyn, which is wrong. I can't see a way to fix this. Am going to ask the contributor if he could provide an inventory for us though.

**Comment by ahankinson** [comment]
Fixed in b9f92d62fb82c3ff48210d900742445eb1a10252

Items will now show Item Composer records, so they can be re-attributed.
