### ISSUE TITLE
Seeing content for Sources in editing display

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#266]
Although I can see the bibliographical entries for a MS if I look at the main entry on the website, it would be useful to have slightly more information in the source editing interface to save constantly flicking back and forth between the two. I am looking at a wiki entry for a MS and adding things where necessary. I can actually get a lot from the bibliographical abbreviation, but if I could see more of the title life would just be marginally easier!

The notes field does seem unnecessarily large in bibliography items linked to sources -- could this perhaps be minimized a bit so that I don't have to scroll so much to get to the bottom of the list?

**Comment by ahankinson** [comment]
More of what title? The bibliography title? I'll look into reducing the size of the textbox widget.

**Comment by juliacmcf** [comment]
Yes, the bibliog title. So I can be a bit more sure whether something I’m thinking about adding is there already or not.
