### ISSUE TITLE
New inventory not showing when sorted by composer

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#268]
https://www.diamm.ac.uk/sources/1536/#/inventory

Source order is showing, as is sorting by title, but sorting by composer is blank
Seems OK in other sources. Might just be a delay.

![screen shot 2017-07-20 at 12 48 56](https://user-images.githubusercontent.com/10816169/28415948-d9b2c87e-6d49-11e7-9c7d-a6a7dd11a955.png)
![screen shot 2017-07-20 at 12 49 02](https://user-images.githubusercontent.com/10816169/28415949-d9b3f398-6d49-11e7-8b9d-013a54d1a6f6.png)
![screen shot 2017-07-20 at 12 49 07](https://user-images.githubusercontent.com/10816169/28415947-d9b2214e-6d49-11e7-8f49-161081746303.png)

**Comment by ahankinson** [comment]
No, it's a real bug. Composer inventories are generated separately, and it's currently not happening when the records are saved.

**Comment by juliacmcf** [comment]
Might be linked, but if I search on one of the works that I put into the composition table a couple of weeks back, and have now hung off an inventory, the search says 'nothing found'. Try
Soleta y verge, which is
https://www.diamm.ac.uk/compositions/89197/

**Comment by juliacmcf** [comment]
Similarly, if I search on 'l'homme arme' I just get a string of composers, no search result for the composition itself (of course I can click through from a composer to their works list, and scroll until I find the work I want, but it's laborious and probably not what a user would expect if searching on a text or work title). Presumably therefore we can't produce search results based on texts? I'm interested in this as I've got someone offering an inventory, and happy to put in composition keys if he can find the compositions in the database.

**Comment by ahankinson** [comment]
There's just a problem with indexing new texts that are added; I've just started a reindex, so you can try your searches again in the morning and it should work.

**Comment by juliacmcf** [comment]
Am I right that it’s not possible to search on texts/titles of works? (i.e. search and get a set of results that is a list of compositions)

**Comment by ahankinson** [comment]
For the moment, yes. But that's a bug that I'm going to fix now, and it should make its way out to the site soon.

**Comment by ahankinson** [comment]
Ok, it's out and reindexing. Give it a couple hours and it should work.

**Comment by juliacmcf** [comment]
Just checking the following is part of the same bug (ignore this if it is);
I’ve just added all the movements of Palestrina Missa o magnum mysterium the database. Now if you search ‘Palestrina missa o magnum’ you get Palestrina, and (for some unknown reason) the Missa O magnum credo *only*. If I click through on Palestrina to the works list I don’t see o mag in the list, but that’s possibly because the list only includes works assigned to pages in manuscripts (it looks that way). What I can’t work out is why only the credo is showing up as a listed composition! Possibly beccause of your indexing bug.

Interesting though: if I take ‘Palestrina’ out of the search criteria, I get all the mass mvts I just put in, but only the Credo is assigned to Palestrina, even though all the compositions have been assigned to him in the composition records.
