### ISSUE TITLE
composer disambiguation

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#271]
We seem to have two composer entries for Palestrina, one with dates and one without. I have not deleted one as presumably both versions are attached to something somewhere. Would it be possible to delete one of them? (the one without the date preferably?).

**Comment by ahankinson** [comment]
Ah! You've finally stumbled upon it. :) I have a solution for just such an occasion.

In the admin interface search for "palestrina" in the People table. It should give you two results.

Click the checkbox next to both of them.

In the "Action" dropdown there's a handy function called "Merge People"

If this is the first time you've done it, make sure "Keep Old" is checked. This is a safety feature. 

Click the 'Change' button.

It will think for a moment and then finish. Select the first one on the list and verify that everything was moved over correctly. 

When you're happy, repeat the process, but this time uncheck "Keep Old". 

You should then be taken back to your listing with only one "Palestrina" record visible, and all of the attachments moved over.

For what it's worth, this is also available on Geographic Areas and Organizations. It's pretty generic functionality, so if you see another table where it would be useful I can add it. (Although I'm not sure how it would do with very complicated records, like sources....)

**Comment by juliacmcf** [comment]
Um, can’t see a ‘Keep Old’ anywhere, and the one action is ‘Go’ not ‘Change’. (I'm using Chrome)

If I hit go, I still have ‘recover deleted people’, and presumably that recovers not only the people but their connections to other objects?

I haven’t done it just in case, but it seems pretty straightforward.

![screen shot 2017-07-21 at 21 00 42](https://user-images.githubusercontent.com/10816169/28480265-bf9117fc-6e57-11e7-88dd-3610be0b7c56.png)

**Comment by juliacmcf** [comment]
I've found another one: composition disambiguation...

<img width="858" alt="screen shot 2017-07-21 at 21 59 10" src="https://user-images.githubusercontent.com/10816169/28482360-e55a4f82-6e5f-11e7-9166-9a7d9399293a.png">

**Comment by juliacmcf** [comment]
Or else I need to be able to see the composition key, so that I can change the composition key on a floater to make it join up to the other instances of the same composition (because the first one in this list is the same as the last)
<img width="823" alt="screen shot 2017-07-21 at 22 01 50" src="https://user-images.githubusercontent.com/10816169/28482643-338f2f46-6e61-11e7-9a77-1938e2218273.png">
...

**Comment by ahankinson** [comment]
If you select merge people and hit 'go' it will take you to a page that will let you 'keep old.'

That dropdown is various actions you can choose to perform on the selected records.
