### ISSUE TITLE
'Contribute a change'

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#275]
Would it be possible to have this link visible even if users are not logged in? That way any user can see that changes can be made, but if they are not logged in and click on it then they are asked to log  in (or create and account). I'm trying to get Meg to use this system rather than send me terse emails, but of course she can't see the Contribute a Change link as she's not bothering to log in. I know it might involve some fiddly code to get that to work, and particularly to get it to go back to the source where the user wants to contribute a change once logged in, but I think it would be worth it.

**Comment by ahankinson** [comment]
It's fixed in develop. It will make it out in the next release.
