### ISSUE TITLE
Window size request!

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#281]
When I'm adding items to a MS and have to create a new composition, the popup window that opens is a bit small. Could you make it wider and taller please? At least tall enough to accommodate the Genre sub-window. I know I'm working on a big monitor, but bigger would be very helpful even on a laptop as I just have to resize it when it pops up.

**Comment by juliacmcf** [comment]
Ditto 'select composition' lookup window accessed from the item editing window

**Comment by ahankinson** [comment]
Unfortunately, no. It's 'hard coded' in Django, with no way to customize it:

https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L35

There is an open issue to change it (https://code.djangoproject.com/ticket/28068) but it has not yet been addressed.

**Comment by juliacmcf** [comment]
Arrr. Thanks!
