### ISSUE TITLE
Difficulty in editing order of items in MS

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#282]
Thanks to aproblem report I've just found a whole load of masses that are listed as 'Mass name: Kyrie'. (I've been trying to fix these, but it's a nightmare as you might imagine, since some of the compositions are linked to other MSS. Anyway, that's not the point of this!) I have a MS that has a load of masses listed as single compositions, and a contributor has given the folio numbers for the individual movements of one of them. That means that all the latter works in the MS have to advance their order number by 4, or the new works appear at the bottom of the MS, or just alphabetically in sequence. I put the same order number as the original item in order to group the movements, but unfortunatley that means the Agnus comes first. If I want them to appear in the correct order I have to advance the order number of each item in the MS by 4 manually. It's a similar issue to the one I raised previously on the URL for an image: would it be possible to have a view for items in a MS where I can edit things like the order number -- and in fact the folio numbers too -- in a list view?

**Comment by ahankinson** [comment]
I've added a section on the Source admin view that will show you just the composition title, the composer, and the source order field. Will that be enough?

<img width="1229" alt="screenshot" src="https://user-images.githubusercontent.com/163183/28641134-01fcdfe4-7246-11e7-9937-d3ad5d869083.png">

**Comment by juliacmcf** [comment]
That looks very useful. Would it be possible also to add cols for the numbering in the source (so if I insert a piece I can quickly renumber all those following it) and also the start and end folio numbers? This will allow us to edit the foliations for e.g. partbooks where we import the inventory for the books from the master list of works, then have to put the foliation in manually. Although we’d still have to edit the actual item record for pages if we have images, if we have no images it would be a very quick way to manage creating new inventories.

**Comment by ahankinson** [comment]
How would you expect that to function? The 'source order' field in the screenshot is the order that it will appear in the source. What do you want to be able to change, and how do you want it to change in response to your action?

**Comment by juliacmcf** [comment]
Well we have the sort order (which is what you’ve put into that display and allows us to account for blanks), but we also have the order number in the source (which seems to have disappeared), which is how people always dealt with partbooks (i.e. 'look at piece no. 5’ because the fol. numbers will be different in each book). Currently in sources with no foliation we just have an ordered list, but if it’s a very long list there’s no help for pinpointing a piece, which I suppose doesn’t really matter.

If we have no ordering within the MS showing, then we don’t need to edit that, but it would be helpful to be able to edit or input the folio numbers from the list view that you showed in your screenshot.

Looks like we have some disambiguation to do… (thank you James)

**Comment by juliacmcf** [comment]
Sleeping on this, I suspect the user display for inventories when ordered by appearance in the MS ought to have the order number within the MS showing: this is because so many studies (and RISM throughout), often refer to 'piece number 72' rather than to a folio number when referring to another MS. All of the RISM incipits that cross-refer only refer to piece numbers, not folios. The use of piece numbering is particularly prevalent in Machaut studies because the ordering of works in MSS is significant, but will also be pervasive in discussions of works in partbooks because they usually don't have folio numbers to go by.
