### ISSUE TITLE
Making images public

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#286]
On the editing-interface display for images in list view it would be immensely useful to have the checkbox for 'public' checkable in this view rather than having to edit each image and then save individually. Could either have the checkbox in the list as for the filename, or have the option in the dropdown at the top (in addition to 'delete images' and 're-fetch IIIF data') for checked images.

**Comment by ahankinson** [comment]
I agree. I'll see what I can do.

**Comment by juliacmcf** [comment]
Thanks. I think I’ll lose the will to live doing this manually on 465 images.

As it turns out, the piece Poppy wants isn’t even in the database, so I don’t know what’s going on!
