### ISSUE TITLE
Scary duplication

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#288]
IN the source view when viewing the inventory arranged by composer there is some crazy duplication going on (see screenshots). I don't think this is source-specific. https://www.diamm.ac.uk/sources/1687/#/inventory/composer
![screen shot 2017-08-23 at 17 17 05](https://user-images.githubusercontent.com/10816169/29626875-1658f778-8828-11e7-81d4-45e2d59e121f.png)
![screen shot 2017-08-23 at 17 15 46](https://user-images.githubusercontent.com/10816169/29626886-1d71d7e6-8828-11e7-85ca-d75ceb9c170d.png)

**Comment by juliacmcf** [comment]
Matthias says all of the entries have Tallis listed twice, and the cycle for the work also listed twice. That doesn't explain why everything is coming up 7 times. I don't if it's relevant that there are 7 partbooks in this set...

**Comment by juliacmcf** [comment]
It looks as if all the short/dorian service works have the composer listed twice. Could this be as a result of Matthias merging the short service with the dorian service compositions? The composer may have been duplicated before, but I didn't notice.

![screen shot 2017-08-23 at 17 37 19](https://user-images.githubusercontent.com/10816169/29627388-db574e20-8829-11e7-96ae-3001f28cf8a2.png)

**Comment by juliacmcf** [comment]
I think this must be a bug in the data for these sources, as it doesn't seem to happen elsewhere.

**Comment by ahankinson** [comment]
I believe this is fixed now; it sorts itself out when the search engine does a re-index.
