### ISSUE TITLE
List of sources for a work has a red herring

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#290]
I'm not sure in the screenshot below why the second MS is listed twice, the second time with no image, and the last MS is also listed twice (but with images). Is this an oddity, or something wrong in the data?
https://www.diamm.ac.uk/compositions/57083/
![screen shot 2017-08-23 at 17 13 56](https://user-images.githubusercontent.com/10816169/29627229-4dd7c2dc-8829-11e7-9c6a-3ad5a2b0ab21.png)

**Comment by ahankinson** [comment]
If you look at the database record for the items attached to this (scroll down to the bottom an click on the 'items' section to expand it) you'll see that they're listed twice there too. MS 36 is listed with both pages and no pages attached; MS 45 is listed with two sets of pages attached.

You can delete the item entries that do not apply, or fix them accordingly.
