### ISSUE TITLE
Problems creating new sources

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#299]
- Can’t add new bibliography items (I think I already raised this in another issue);
- We don’t seem to be able to add any provenance to a MS in the Source view or in the SourceProvenance table, as in that table it wasn’t able to find the MS we had just entered;
- Matthias says sometimes he saves notes in the source information and they are not being saved, but I asked him to add a test one and it was OK so maybe it's intermittent
- At the the bottom of the Source editing page there is a button to add items, but you can’t as most of the fields are not editable (not a problem as we know we need to go to the item table to add items, as they have to be also linked to compositions, so probably a good idea to remove 'add item', or else make the fields a bit more editable, so we can find the items linked to the MS in the Item table later and add detail);
- In the list of page types, we need additional items for pastedowns and offsets (both of which are in bindings, but not binding pictures).

**Comment by ahankinson** [comment]
It's easier for me if these are all separated out, since I can address them one at a time and provide individual feedback on their progress (and whether it's doable / not doable, etc.)
