### ISSUE TITLE
User-friendly error report for saving a problem report that is unattached to an object

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#307]
I clicked add a report, then typed my error report in (it was about a genre, so I couldn't submit it from the main site) but when I hit save got a server error.

**Comment by ahankinson** [comment]
You probably have to attach it to an object in the database. I would file bugs like that here, rather than filing a problem report.

**Comment by juliacmcf** [comment]
OK. Just didn’t want to overdo minor issues on Github!

**Comment by ahankinson** [comment]
It's where I can keep track of things. File as many as you need; I would prefer they are here rather than in two places.

**Comment by ahankinson** [comment]
I'll leave this open as a reminder to make a more user-friendly error message when submitting an error report without attaching it to something.

**Comment by juliacmcf** [comment]
No need!
