### ISSUE TITLE
Unable to add bibliography items

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#309]
I thought we had reported this before, but can't see a report, so apologies if it's a duplicate. There were various problems with editing bibliography entries on sources, but in fact we can't create new bibliographical records for books/articles not in the database at the moment, nor can we add new bibliographical citations to a source. (cf list of outstanding problem reports!).

**Comment by juliacmcf** [comment]
Building up quite a backlog of bibliographical items that need to be added...

**Comment by ahankinson** [comment]
Hopefully this is fixed now.
