### ISSUE TITLE
Editing items in inventories

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#328]
If you edit an item, when you hit save the system then jumps back to the complete list of compositions, instead of the found list, or the previous screen if you were editing the item from the item list on the Source page.

So...
editing the Source, I scroll down to 'Items', open the dropdown;
click on an item, edit it, hit save;
page goes to the complete item list, not back to the previous page

Ideally I'd like to be able to edit the foliation in the list view.

**Comment by juliacmcf** [comment]
<img width="1403" alt="screen shot 2017-10-04 at 18 40 16" src="https://user-images.githubusercontent.com/10816169/31190735-e318652e-a933-11e7-9166-fe2fec64ad21.png">
<img width="1402" alt="screen shot 2017-10-04 at 18 40 32" src="https://user-images.githubusercontent.com/10816169/31190737-e34974a2-a933-11e7-96df-bd9cf2001871.png">
<img width="1402" alt="screen shot 2017-10-04 at 18 40 39" src="https://user-images.githubusercontent.com/10816169/31190734-e317392e-a933-11e7-856d-385d3ea2aaa3.png">
<img width="1403" alt="screen shot 2017-10-04 at 18 40 46" src="https://user-images.githubusercontent.com/10816169/31190736-e31a8d22-a933-11e7-9f02-b9d4e882634a.png">

**Comment by juliacmcf** [comment]
If you go from the composition search table, when you edit an item and save it goes back to the found list, so the problem is only if you're editing via the source page.

**Comment by juliacmcf** [comment]
PS: I'm trying to put foliation into the Anne Boleyn book (MS 1070) inventory. I haven't attempted to add pages as there are hundreds.

**Comment by ahankinson** [comment]
Are you trying to create pages because you have images? If you give me the folder name and the source key I can do this automatically.

**Comment by juliacmcf** [comment]
Folder name is: GB-Lrcm_1070
SourceKey is: 2033
