### ISSUE TITLE
usability request on edit interface

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#330]
When I'm adding items I click through to the composition table to select the composition. Would it be possible to make composition key numbers visible here? In this example I want to add all mvts of a mass consecutively, but each time I have to click through. If I can copy down the key numbers I can just type those in, saving some time. See screenshot. (I don't want to lose the 'appears in' column, as it's very useful to work out which piece to choose when there are many with the same name).
<img width="812" alt="screen shot 2017-10-23 at 14 23 12" src="https://user-images.githubusercontent.com/10816169/31891318-f1bead58-b7fd-11e7-9d49-06222e2d5e8c.png">

**Comment by ahankinson** [comment]
Yes, I've already fixed this on the development version, I just haven't deployed it to the production version.

**Comment by juliacmcf** [comment]
Yaaay!

**Comment by ahankinson** [comment]
This should now be live.
