### ISSUE TITLE
Bibliography pages problem

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#332]
https://www.diamm.ac.uk/admin/diamm_data/bibliography/141/change/

The pages are screwy: the author published the article over 2 journal issues, so it needs to allow two volume numbers for the journal, and to have a rather complex series of page numbers. This isn't being managed correctly here.

<img width="1187" alt="screen shot 2017-10-23 at 15 52 38" src="https://user-images.githubusercontent.com/10816169/31895884-41c4f72e-b80a-11e7-96cf-614ab35f0ce2.png">
<img width="682" alt="screen shot 2017-10-23 at 15 52 52" src="https://user-images.githubusercontent.com/10816169/31895885-41e5899e-b80a-11e7-957c-4ee989316c4a.png">

**Comment by ahankinson** [comment]
Sorry... hit the wrong button

**Comment by ahankinson** [comment]
This may have been fixed but I can't find a page that mentions this bibliography item.

**Comment by juliacmcf** [comment]
When it was listed it didn't show on the website, but was in the editable list. I assume it wasn't showing because of the screwed up page numbers, so fixed that and then it showed.
