### ISSUE TITLE
Bibliography author problem

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#333]
I've just added two new items to the bibliography which entailed also added a new author, plus two more people who are editors. unfortunately, although those names are showing up in the edit interface, they're not appearing in the online version. I've done some re-loading; deleted the entries from the source and re-added them, but still no dice. I have added some other new biblio entries, and this seems to be to do with having added a new author to the author table. Existing authors show up fine.
<img width="929" alt="screen shot 2017-10-23 at 16 01 40" src="https://user-images.githubusercontent.com/10816169/31896528-ebd3bf38-b80b-11e7-81f5-f0ef85f9fc8d.png">

**Comment by ahankinson** [comment]
Bibliographies are pretty complicated to assemble and format. I may have to re-index. Could you give me a link to this page?

**Comment by juliacmcf** [comment]
It's here: https://www.diamm.ac.uk/sources/119/#/bibliography

**Comment by ahankinson** [comment]
This is fixed with a re-index.
