### ISSUE TITLE
bibliography display editor glitch

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#334]
There's a stray 'and' when there's only one editor...
<img width="847" alt="screen shot 2017-10-23 at 16 06 55" src="https://user-images.githubusercontent.com/10816169/31896642-37449406-b80c-11e7-9104-0eb9eec88588.png">

**Comment by ahankinson** [comment]
Please include a link to the record in the admin, and also on the site, so that I can check it out.

**Comment by juliacmcf** [comment]
https://www.diamm.ac.uk/sources/119/#/bibliography

https://www.diamm.ac.uk/admin/diamm_data/bibliography/6149/change/

**Comment by juliacmcf** [comment]
I don't think this is just in one source, I suspect it's a general glitch, which is why I didn't give links to the specific entry. (I did check the entry just in case there was a blank editor screwing things up).
