### ISSUE TITLE
chapters in books -- which are already in the database

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#336]
Would it be possible when adding chapters in books to be able to assign them to the book if it's already in the database? It would ensure the references to the book are all identical (and if I discover something is incorrect I only have to change the parent entry), but it may be a bit too fiddly to try and create a self-reference within the bibliography table.

**Comment by ahankinson** [comment]
Unfortunately, no -- it's not set up to do that, and it would probably be a lot of work (and quite a few hacks) to do it. Sorry.
