### ISSUE TITLE
Crediting description authors

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#337]
This is a slightly crucial one, as we want particularly senior scholars to contribute descriptions and for users to see who has contributed the description as a way of seeing whether it's someone who knows their stuff or not. It will also give kudos to DIAMM to have work by important people on the site. Could we therefore have the author of the description given alongside the heading 'Description'?

There's a caveat: I don't want all the rewrites that James did to show up with him as author, as he didn't write them, he just edited them from the catalogues. Could you change ALL the ones attributed to James to just 'DIAMM, 2017'?

**Comment by ahankinson** [comment]
I've updated the records to say "DIAMM, 2017" -- that's live now.

**Comment by juliacmcf** [comment]
By live do you mean visible on the public website? I was hopping we could have an author credit beside the main description field. I just did an update for the description of https://www.diamm.ac.uk/sources/4073/#/ and promised the author I would credit him, but it's only showing a DIAMM 2016 credit in 'contributors', and it would be diplomatically best if the author could be credited alongside the word 'Description' on the default view.

**Comment by ahankinson** [comment]
I just meant that I've changed all the entries that mentioned James to mentioning DIAMM. 

If you want the person to appear in the contributors, add a new "Problem Report" record for that person and attach it to that source. You can describe what they do, then accept it. It should automatically put their name in the contributors section. 

I'll see what I can do about adding their name beside the description field.

**Comment by juliacmcf** [comment]
Yes, contributors not a problem (thank you for changing the James thing BTW!), but it would be good to credit the author of the original description, as any changes would be to the main description and might thereby obscure the original contribution

**Comment by ahankinson** [comment]
Have a look at the site when you get a moment and let me know what you think.

**Comment by ahankinson** [comment]
PS, I've hidden any notes with "DIAMM, 2017" as the author, as that was most of them and it just looked a bit silly.

**Comment by juliacmcf** [comment]
good idea.

now GO TO BED.

**Comment by juliacmcf** [comment]
not seeing anything different…

**Comment by ahankinson** [comment]
Hold down shift and press the refresh button; you should see the name in the bottom right.
