### ISSUE TITLE
Live images

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#340]
I note that quite a lot of images are still not live on the website. The spreadsheet shows that a lot of the Spanish images have not been linked, and I wonder if this is because there were no page records for them in the FM DB?
https://docs.google.com/spreadsheets/d/1C-uUXIRTnr4t_Wa2_ch5aTF7d2iucAP8r_qcnz9Z_9I/edit#gid=140362103
I was just trying to add some images for a MS requested from Seville Cathedral (E-Sco_5-1-43), but can't link them to the MS even with the correct file path for the image, as every time I select the MS and fill in page information this is apparently not valid. Do I have to make 'Pages' first? If so then it looks as if we have some multiple page records that would need to be created _en masse_ via import from an excel file (probably).

**Comment by ahankinson** [comment]
The minimum I need to link the images is a source key. For E-Sco_5-1-43 there is no source key listed.

**Comment by ahankinson** [comment]
If you can provide me with a source key for these sources, I can link them automatically. Then you don't need to create the pages.

**Comment by juliacmcf** [comment]
SourceKey for this one is 741

Slightly surprisingly, as I would have expected this one to have a much higher key number!

**Comment by juliacmcf** [comment]
I'll go through the spreadsheet and put the key numbers in

**Comment by ahankinson** [comment]
I'm going to close this since most of the the Spanish MSS have been handled, with one exception. (E-G_frags, which will need special consideration).
