### ISSUE TITLE
city problem?

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#341]
Email string...
-----------------
I was ‘browsing’ by country, under England, Oxford.  I tried a few other cities that worked and some that did not

THe following worked: Canberra, Berkeley, Beverley, Bury, Dorchester, Exeter,

THe following did not:  Arundel, Cambridge, Canterbury, Durham, Gloucester, Oxford, London.

---------------
On 14 Nov 2017, at 08:19, Julia CMcF <julia.cmcf@gmail.com> wrote:

Are you searching on ‘Oxford’ or clicking on an Oxford link somewhere?

----------------
On 14 Nov 2017, at 13:17, Margaret Bent <margaret.bent@all-souls.ox.ac.uk> wrote:

Still getting Server error for Oxford and some other places. Some cities work and some don’t.

-------------
On 14 Nov 2017, at 07:59, Julia CMcF <julia.cmcf@gmail.com> wrote:

I’ve fixed them.

However, I feel it might confuse people not particularly aware of the makeup of the UK to search e.g. for libraries in England and not find either of those. My preference is for UK or GB.
I suppose doing it this way saves a revamp if Scotland secedes!

-------------
On 14 Nov 2017, at 12:55, Margaret Bent <margaret.bent@all-souls.ox.ac.uk> wrote:

Bangor and Paisley are not in England….. I thought they had previously been listed as GB or UK?

**Comment by ahankinson** [comment]
I am also getting a server error for Oxford; I will look into it.
