### ISSUE TITLE
Migrate comments from old site

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#35]
Comments from the old site are in the database, we just need to figure out how to bring them over and attach them to the appropriate new user accounts. This will depend on first building a comment function in the new site, which will be filed as a separate issue.

**Comment by belljustin** [comment]
Is the issue for building a comment function already filed somewhere?

**Comment by ahankinson** [comment]
This is different. There's a "Contribution" function that Arielle is working on, but we will also want people to post public and private comments on a source.

**Comment by mscuthbert** [comment]
For reporting purposes (funders, etc.) can you give the board a sense of the total scope of the comments when you make a transfer: i.e., 2000 comments (800 private 1200 public) by 50 unique users. etc.  Thanks!

**Comment by ahankinson** [comment]
@mscuthbert Rough numbers are that I've transferred 605 private "page" comments and 124 public "page" comments. (These haven't been exposed on the front-end just yet since we don't have an interface for viewing or creating them yet...). I can't get the uniqueness of the users offhand (would need to write a query for the DB and I'm in admin  mode :) .

Source comments were fairly negligible -- 3 private and 1 public.
