### ISSUE TITLE
Incorrect information on set view for group of manuscripts

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#372]
Wode partbooks: the individual books come up correctly with images showing, but the set description says that there are no images available for any of the books, which is incorrect. Not sure where this is coming from.
<img width="1143" alt="screen shot 2018-01-17 at 14 51 29" src="https://user-images.githubusercontent.com/10816169/35048842-24ff2db0-fb96-11e7-966d-a5086ba7ec4f.png">

**Comment by juliacmcf** [comment]
https://www.diamm.ac.uk/sets/172/

**Comment by ahankinson** [comment]
Got it.
