### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#38]
```
  File "/Users/ahankins/Documents/code/git/diamm/diamm/urls.py", line 39, in <module>
    from diamm.views.feedback import FeedbackView
ImportError: No module named 'diamm.views.feedback'
```

The feedback view is imported in `urls.py` but has not been committed, which breaks the build. This should be fixed ASAP.

**Comment by ahankinson** [comment]
@ariellegoldman has this been fixed? I believe it was on your branch

**Comment by ariellegoldman** [comment]
yes, it was fixed in the updated about menu. I forgot to close it.
