### ISSUE TITLE
Something wrong with searching on composers in main search page

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#381]
I put John Sheppard in the main search box, and also tried putting him in the composer box, but the results showed only 2 works. However, when I clicked on his name in the first search I got the full list. Something wrong here?
<img width="882" alt="screen shot 2018-07-16 at 10 11 04" src="https://user-images.githubusercontent.com/10816169/42750887-cc7cb5bc-88e0-11e8-8715-a889fb082b6a.png">
<img width="1181" alt="screen shot 2018-07-16 at 10 11 33" src="https://user-images.githubusercontent.com/10816169/42750890-cf007076-88e0-11e8-9aaa-ea6d1e7447ca.png">

**Comment by ahankinson** [comment]
I'm not seeing that?

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/163183/42751046-5792524c-88e1-11e8-8606-ec5a1d73ec56.png">

**Comment by juliacmcf** [comment]
I’ve copied your search and get this! I clicked in the main box at the top and hit return to get it to re-search, but no change.
