### ISSUE TITLE
Notation description

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#390]
I've just tried to add a 'notation' to a source, but only got the free-text description field. I can't find the field that was completed from an authority list. Has that gone?

**Comment by ahankinson** [comment]
It's still there:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/163183/43678937-618c96b2-9814-11e8-8b24-00c2d2f0ebc6.png">

**Comment by juliacmcf** [comment]
That wasn't showing when I was editing the source description. It's there on another MS -- I suspect it didn't appear because there were no notations selected in it for that particular MS -- can't remember which one it was, sadly.
