### ISSUE TITLE
Latest date override for people

### ISSUE THREAD

**Issue by mscuthbert** [diamm/diamm#391]
I thought I was doing the right thing in changing "Latest Date" for Zachara (https://www.diamm.ac.uk/people/132/) to 1416, since that's the latest date he could be alive, but this also updates the date range for the "ca." value -- the display of ca. 1350-ca. 1413 is correct -- he's probably dead in 1413, but the first confirmation that we have for his death is 1416.  Just wondering if we want to keep separate "earliest" and "earliest probable" and same for latest.

Enjoying fixing a few things here and there.  - M

**Comment by ahankinson** [comment]
Unfortunately there is no correct solution for all people, and the trade off is one that has the closest meaning with a manageable amount of logic for all the cases. 

The intention of the date fields are that they can be used as numerical sorting and filtering fields. If you want to be more specific, suggested editorial practice is to add a date note for that person. So it’s largely a judgement call on the part of the editor what they want to put in as a numeric value. If it were me I would probably say ca. 1413, with a date note specifying the evidence

**Comment by mscuthbert** [comment]
Thanks!  Noted and closing!

**Comment by ahankinson** [comment]
Thanks for taking the time to raise the issue, though. It’s appreciated.
