### ISSUE TITLE
Formatting in source description; Physical Description

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#406]
Although the html preview is correct for the physical description here, 
https://www.diamm.ac.uk/sources/4734/#/
The web display loses the line-breaks. 
Authorship of this section is not showing

**Comment by ahankinson** [comment]
If you want a line break, end a line with two (or more) spaces and it will insert a `<br />` tag.

**Comment by ahankinson** [comment]
The reason authorship does not show is because it automatically hides it if it contains "DIAMM" (since you didn't want it to show if it was just a DIAMM description). So I would actually put the person's name who did the description (i.e., yours)

**Comment by juliacmcf** [comment]
It did have DIAMM and Meg Bent (who did the diagram — cool by the way that I can upload pictures!!!), so does it exclude it if ANY word in it is ‘DIAMM’?

Thanks for the tip about spaces BTW.

**Comment by ahankinson** [comment]
https://github.com/diamm/diamm/blob/master/diamm/static/apps/source/src/components/containers/description.js#L269

Yes; 'indexOf' in this context will look for the string "DIAMM" and, if found, will not show the author.
