### ISSUE TITLE
Launch of Beta site (?)

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#41]
The programme for the Med-Ren conference in Sheffield has timetabled a short session for three projects to launch their new websites, and includes DIAMM. The date is 6 July at 14.30 BST.

**Comment by ahankinson** [comment]
Would this be the full site, or the public beta?

**Comment by juliacmcf** [comment]
I'm not expecting the full site to be ready for Med-Ren, so it’s public beta or something that will at least show people where we’re going if public beta isn’t ready. Would it be possible to have user accounts and images working at this point, or will images require full IIIF functionality (still no response from Bodley about their estimate)? Even if we tell Bodley to go ahead I can't imagine they would ingest before the end of the year (particularly with quite a few of their delivery systems broken at the moment)... or will you set up your own test IIIF system at McGill to see if you can do it and make it all work before transferring it elsewhere? Everything else can be in an unfinished state: as Myke said, it’s already better than the old site and all it needs is user accounts and images to blow the old one away!

**Comment by ahankinson** [comment]
I believe this has been addressed. 😄
