### ISSUE TITLE
Display issue in set description

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#414]
Although the preview of the description field in the admin interface appears to accept line ends in the layout, they don't display on the live site -- there aren't many descriptions that need them, but this one does. We're trying to work out how to deal with sources that are part of a whole, so if we put a complete inventory on each fragment it's misleading, but it's almost as misleading not to show where the fragment fits in the reconstructed whole. This is not something that I suspect could be easily sorted out (ideally one would gray out the parts of the inventory not included in each fragment).
<img width="744" alt="screen shot 2019-01-05 at 14 56 53" src="https://user-images.githubusercontent.com/10816169/50725766-9b025300-10fa-11e9-9704-0ca678777e07.png">
<img width="1170" alt="screen shot 2019-01-05 at 14 57 14" src="https://user-images.githubusercontent.com/10816169/50725767-9b025300-10fa-11e9-8f78-9ec1e51849d2.png">

**Comment by ahankinson** [comment]
The answer is here:

https://github.com/diamm/diamm/issues/406#issuecomment-441082929
