### ISSUE TITLE
inventory sort order

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#415]
I've noticed with a few MSS that the inventory sort order is screwy -- this is usually where there are roman numerations for the folios. One example is sourceKey 98. Would it be possible to ensure the inventories are sorted by the sort order, and not by the foliation?

**Comment by ahankinson** [comment]
I can change it to order on the 'source order' field. 

However, this may be a case of being careful what you wish for.

The 'source order' field is translated from the old database. There are some items (~13, keys listed below) that do not have any value in this field). The others are given as an absolute value of ALL source orders in the database (for example, the Eton Choirbook starts at 3646 and ends at 3738). It is no longer necessary to do this, but mixing old and new numbering will likely require re-ordering ALL inventory items. In other words, if there needs to be a new inventory item inserted between 12345 and 12346, all sort order items in that inventory will need to be updated. 

New sort order entries should start at 1 and go up.  

(The 'old' way of using floating point numbers, e.g., 123.1, 123.2, is no longer possible. Numbers in sort order MUST be whole numbers). 

Items without source order value:

- 111830
- 113159
- 115201
- 114238
- 113133
- 115194
- 111840
- 115200
- 115198
- 111810
- 115199
- 113132
- 114239

**Comment by ahankinson** [comment]
This is now fixed.
