### ISSUE TITLE
Case sensitivity in searches (recommendation: NO!)

### ISSUE THREAD

**Issue by mscuthbert** [diamm/diamm#42]
in the Beta:
leiden 2515 does not find the manuscript it should refer to, but Leiden 2515 does. (screenshot)

It appears that some fields are being indexed case sensitively and others are not, and Shelfmark, etc. 

(oh, and tiny annoying extra space between fragment and 14th c.)
<img width="462" alt="screen shot 2016-05-29 at 14 57 59" src="https://cloud.githubusercontent.com/assets/3521479/15635510/cd3b0ba4-25ad-11e6-9664-7f3da8ad9133.png">

**Comment by ahankinson** [comment]
Thanks, Myke. Fixed in master, should be rolled out next time we update the beta site.

The extraneous space issue was fixed in 337956f7640382d9a6e01a5b52e36a65de7fb59d

![image](https://cloud.githubusercontent.com/assets/163183/15638753/65480544-25f1-11e6-926e-d82809d5a870.png)
