### ISSUE TITLE
Editing easement request

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#424]
We have spotted a problem in the data for a MS with 328 inventory entries where the start and end folio information has been scrambled and needs fixing. (SK 870).

Would it be possible to allow editing of the start and end folio fields in the list display? Don't worry if this is a massive edit to your scripts, but it would almost certainly end up being useful in the future if we're putting in inventories from scratch.
<img width="802" alt="screen shot 2019-02-18 at 12 15 21" src="https://user-images.githubusercontent.com/10816169/52950541-64655c80-3377-11e9-9ad8-8e16bfdf8250.png">

**Comment by ahankinson** [comment]
Yes, that should be a pretty easy fix.
