### ISSUE TITLE
Search hiccup

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#429]
Sources are turning up more than once. No idea why. Same source keys. Could it be happening if we edit documents so old and new versions are showing up for each save iteration? We have noted it with ones that we're editing.
![Screen Shot 2019-03-15 at 17 06 36](https://user-images.githubusercontent.com/10816169/54448997-009b3d00-4745-11e9-861f-43ffeda352ed.png)

**Comment by ahankinson** [comment]
I think I've fixed it. I'm re-indexing so it should go away, but if you could keep an eye on the records you edit and see if you get doubles again, let me know.
