### ISSUE TITLE
Bibliography: display sort order

### ISSUE THREAD

**Issue by fattoxxon** [diamm/diamm#431]
another 'random' display order. Clearly not alphabetical; and the biblio 'ID' numbers for the first few on the attached image are: 4342, 1869, 730, 749, 676, 2138, ... so it's not even sorted in ID order.

Could we have an **alphabetic display (by author)** please, this would be most helpful for end-users, especially when there are long lists (some bibliographies have dozens of entries)

![Screenshot (140)](https://user-images.githubusercontent.com/37849857/54527296-5f44fe80-4971-11e9-9cb2-143d9ce8a892.png)

**Comment by ahankinson** [comment]
It's displayed in chronological order, with newest first.

**Comment by ahankinson** [comment]
I'm going to close this one. The display order is chronological, and I won't have an opportunity to create functionality to display them in a different order.
