### ISSUE TITLE
Edit text on login page

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#434]
It is helpful for people who don't use the site often to be reminded of the requirements for passwords (e.g. how many characters/whether you have to use letters/numbers etc.) on the login page. Sometimes I don't know whether I used one or another of my regular passwords, but the requirements might remind me. If I type in the wrong one then I get a reminder that it must contain 8 characters, so having that up front might be helpful?

**Comment by ahankinson** [comment]
I have added this to the next release. Note, though, that there aren't really a whole lot of restrictions that are easily explained -- it has to be minimum 8 characters and can't be completely numeric. However, it also cannot be on the list of the 20,000 most used passwords*, and cannot be your e-mail address, or first or last names.

 * https://gist.github.com/roycewilliams/281ce539915a947a23db17137d91aeb7
