### ISSUE TITLE
Menu oddity on front page

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#436]
I notice that the Anne Boleyn book is not in the list of DIAMM publications, even though it has a page as a child of the Publications main page. Do I need to do something special to add it to the main menu?
<img width="839" alt="Screen Shot 2019-04-27 at 12 14 11" src="https://user-images.githubusercontent.com/10816169/56848952-21c77f80-68e6-11e9-9c4d-7efaaa28daa6.png">

**Comment by ahankinson** [comment]
In the Wagtail editing page there's a "Settings" tab, with "Show in menus":

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/163183/56848984-85ea4380-68e6-11e9-8ab7-4c7fa8efaadc.png">

It should appear now.

**Comment by juliacmcf** [comment]
Arrrr
