### ISSUE TITLE
browser access problem -- not browser issue

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#437]
Matthias is sitting next to me using a DIAMM laptop basically configured the same as mine. I can access the DIAMM website, but he can't on Chrome, Safari or Firefox. I have checked the network settings and there's nothing odd; we've also tried with the Oxford VPN running, and still no dice. There have been a couple of people who have reported this sort of difficulty in accessing the site. It's obviously not a browser issue, but it must be something else. Firewall is off. If we could run this to earth we might be able to help other people with the problem. For now it's just annoying as Matthias can't work out in the garden! We have tried two wireless networks. It works fine for me, but not for him. I'm going to try the laptop on a wired connection to see if that helps.

**Comment by ahankinson** [comment]
Fixed.
