### ISSUE TITLE
images not loading

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#439]
I don't know if this is just because I've just added the image, but in this source
https://www.diamm.ac.uk/sources/4749/#/
The image shows up in the preview, but when I click the images tab nothing loads. It seems to happen with quite a few sources and we can't see what the blockage is.

**Comment by ahankinson** [comment]
Seems like it's appearing now?

**Comment by juliacmcf** [comment]
This is happening for a number of sources: the images are there and appear to be loading in the admin interface. However we have to reload them manually to make them show up. Matthias fixed this. I’ll make a note that this is how to handle the problem! You can close it unless there’s a way of fixing it!

**Comment by ahankinson** [comment]
This is fixed now.
