### ISSUE TITLE
A confusion of concordance

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#440]
In the inventory listing for a work, there is a sometimes a list of abbreviations for concordant sources. This seems to be at odds with the list generated if you click on the composition title. e.g.
https://www.diamm.ac.uk/sources/2272/#/inventory
Sadler Mus.e.1 piece starting on 38v (Tallis Lamentations) gives 
Concordances
RCM2035; Tenb. 1469; Tenb. 369; Merro; Drexel; BL5059; BL32377; BL34726
But none of these are in the list for the composition, nor are any of the sources that are actually concordant listed under the composition in that concordance list.
https://www.diamm.ac.uk/compositions/57073/
GB-Lbl Add. MS 32377 (62v—65r) 
GB-Och Mus. 979-983 (Baldwin Partbooks)
GB-Cp MS 35, 37, 44 (Peterhouse Partbooks: Latter Caroline Set)

We have found the data, which is a concordance 'note' in the item entry, however the information is misleading because it is based *only* on MSS for which we don't have inventories.

I think really we should remove the display here of the concordance note if possible, as it's misleading. If that's not possible it needs to be retitled something like 'concordances not inventoried in DIAMM'.
Ultimately an abbreviated list of concordant sources would be very useful in this position, but I don't know if you can generate one automatically. Perhaps a feature request for later?

**Comment by ahankinson** [comment]
Could you not just delete the concordance note, if it's not correct or is misleading?

**Comment by juliacmcf** [comment]
Trouble is, we'd have to find them all, and I don't know what compositions they're attached to. I don't want to lose the information altogether. Could we just suppress that information in the online display for now?
