### ISSUE TITLE
Getting from admin area to live site

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#442]
It would be immensely useful if when we've finished editing a document description we were able to click on a link at the top of the admin page to take us to that source on the live site view. At the moment we have to open a new window and do a search, then click on the thing we want in the search results in order to check that a change has been correctly implemented, which is frustrating. An easy link would be much appreciated!

**Comment by ahankinson** [comment]
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/163183/58933047-f2662700-875d-11e9-8c1a-ff07e0713152.png">

There is a 'View on Site' button in the top bar already?

**Comment by juliacmcf** [comment]
It just goes to the main site, not to the particular source on the site. It’s a pain when reading problem reports as we have to wiggle around finding the source to then edit it.

**Comment by ahankinson** [comment]
I've just checked it and it seems to work as expected -- it takes me to the source page, not to the main page. 

Can you provide any more information about when or why it doesn't work for you?

**Comment by juliacmcf** [comment]
There is a ‘view on site’ button on the source page, but what would be really useful would be one on the problem reports that takes you to either the live source page or the admin version, as getting to the source record to edit it takes loads of fiddling around.

**Comment by ahankinson** [comment]
Ah! I didn't know that you meant on the problem reports page. I'll see what I can do.
