### ISSUE TITLE
Bibliography compilation error

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#446]
If we make a new entry for a book and call it an edition rather than a book, the publication information (publisher and place) are chopped off the end of the entry. This only shows if the edition is listed as a 'Book'.

if an edition, shouldn't the title be italicised as for a book? I'm not that familiar with Chicago style...

**Comment by ahankinson** [comment]
If you add additional entries to the bibliography type table they won't automatically get recognized as having the appropriate styling. [The rules](https://github.com/diamm/diamm/blob/master/diamm/templates/website/bibliography/bibliography_entry.jinja2) for generating bibliography entries are only based on the [types that are known](https://github.com/diamm/diamm/blob/master/diamm/models/data/bibliography_type.py), and any additional types are assigned a 'default' which may or may not include specific types of information. 

That said, I think I've fixed this particular issue to make an edition behave like a book.
