### ISSUE TITLE
Image not showing Mus. e. 3 (SK 2274)

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#453]
I'm a bit stumped on this one: 48v is not showing up when scrolling through the images, yet...
The image is in the image list for the MS and has the correct order number;
The image is correctly connected to the page list for the MS and the image shows up in the IIIF response so is on the server in the correct folder;
The image is correctly connected to the inventory items it refers to.

It just isn't among the images when you scroll through the MS, but the others are loading, so it doesn't appear to be corrupt or it would break the whole MS.

https://www.diamm.ac.uk/sources/2274/#/images
If you type '48v' into the 'Go' box you get to folio 49.

**Comment by juliacmcf** [comment]
Image also not showing up, though in this case it's there: https://www.diamm.ac.uk/admin/diamm_data/image/14174/change/?_changelist_filters=q%3DGB-Cpc_493

This image causes the viewer to crash, but appears on the IIIF page to be OK. If I jump to the following image and scroll back the image starts to load, but then the viewer crashes. This could however be a corrupt image, so may be a different issue altogether.

**Comment by juliacmcf** [comment]
(Actually, scrolling backwards at all from anywhere in this image set causes the viewer to crash).

**Comment by juliacmcf** [comment]
OK, update (sorry). Image 21v of Peterhouse is there and showing, but scrolling backwards makes the viewer crash, and in fact just sitting looking at an image in this set makes the viewer crash.

**Comment by ahankinson** [comment]
Mus e. 3 is fixed now. I've identified the problem with Peterhouse and am working on a fix. Stay tuned...

**Comment by ahankinson** [comment]
Peterhouse is fixed.
