### ISSUE TITLE
Strange inventory note proliferation

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#457]
https://www.diamm.ac.uk/sources/635/#/inventory
If you click open the first piece in the inventory, you see a long list of notes (see screenshot). I don't know where these notes are coming from (they are obviously not to do with this work), and when I click on edit the only note that is in the record is not actually showing up in this list.
<img width="1488" alt="Screen Shot 2019-08-30 at 11 19 39" src="https://user-images.githubusercontent.com/10816169/64013704-53608980-cb18-11e9-92ef-f9a3099dbd3f.png">

**Comment by juliacmcf** [comment]
Also, when I add notes to inventory items they are not showing up, but that may be an indexing issue?

**Comment by ahankinson** [comment]
This seems to have been fixed by a re-index.
