### ISSUE TITLE
bibliography content not updating

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#458]
I've added a new bibliography entry to GB-DRc MS C.I.20, but what's showing up is missing the author and journal name. I'm hoping this is just a re-indexing issue.
[No Author] 2018/1. Philippe de Vitry in England: Musical Quotations in the Quatuor Principalia and the Gratissima Tenors. .
<img width="670" alt="Screen Shot 2019-09-05 at 19 05 51" src="https://user-images.githubusercontent.com/10816169/64368738-ce430c00-d012-11e9-85d5-682cf8f5afec.png">
<img width="1013" alt="Screen Shot 2019-09-05 at 19 06 00" src="https://user-images.githubusercontent.com/10816169/64368739-ce430c00-d012-11e9-9a1f-4cbfa5a32aa7.png">

**Comment by ahankinson** [comment]
A reindex has fixed this.

(Why is there a `/1` in the year?)

**Comment by juliacmcf** [comment]
It’s an oddity with the volume numbering and this was the only way I could find to express it. I think it is 2018 volume 1 for the year, but volume 9 overall. The original citation was:

Elina G. Hamilton, "Philippe de Vitry in England: Musical Quotations in the Quatuor Principalia and the Gratissima Tenors," Studi Musicali, Nuova serie, anno 09, 2018, n. 01, pp. 9–46.

I suppose the /1 could have gone into another field. What do you think?

**Comment by ahankinson** [comment]
That looks like an issue number... I would express it as "vol. 9, no. 1" or "9 (1)".

The years are used for sorting the list chronologically in the bibliography. It should still work if you put non-numbers in there, but it may not always work as you expect.

**Comment by juliacmcf** [comment]
OK
