### ISSUE TITLE
Server error with account profile

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#459]
If I click on 'Your Account' or 'Your Profile' when logged in I get a server error.

**Comment by ahankinson** [comment]
It works for me? 

What happens if you visit https://www.diamm.ac.uk/account/ directly?

**Comment by juliacmcf** [comment]
Same Server error, but no specifics

**Comment by ahankinson** [comment]
Can you try it again, please?

**Comment by juliacmcf** [comment]
No dice in Chrome…

Just tried in Safari and had to input my account details as they weren’t remembered. I have logged in, but got straight to a server error message without trying anything else. No problem getting to the admin interface though.

**Comment by juliacmcf** [comment]
Still get server error if I try to get to my account. weird.
