### ISSUE TITLE
diva bug

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#460]
If I attempt to scroll through images in some manuscripts the viewer crashes. I don't know if this is to do with the images or not. One source where it happens is https://www.diamm.ac.uk/sources/572/#/images
I've tried scrolling slowly; waiting to scroll until the images have had a chance to load; using the diva-window scroll bar to click down to the next window; dragging images up. Always seems to crash in the same place.

**Comment by ahankinson** [comment]
This is now fixed. You may need to clear your caches and refresh the page to reload the JavaScript with the fixes.
