### ISSUE TITLE
Bulk item create & '502 Bad Gateway'

### ISSUE THREAD

**Issue by fattoxxon** [diamm/diamm#462]
I know Julia has several bulk jobs on her wishlist: here's mine. I need to create ~150 new items on an MS that is already quite big [Grimma 49, but this potentially affects other big mss too]. The 'Add item' button on source would normally be ok - I could add 10 or 15 at a time, a bit tedious but manageable. But with big sources like this I get '502 Bad Gateway' if trying to add several items at once & can often only add 1 or 2 items at a time. Sometimes even adding 1 item gets bad gateway & then I can't add anything... 

Adding 150 items one at a time is definitely not going to work. 2 possible approaches to a solution:
 - a mechanism to add items to a source without updating the rest of 'source'; item list already allows modify but not add, maybe add items via item list; or maybe (preferably?) modify 'change source' to de-couple item changes from other source changes so that server workload is reduced - though I'm worried that could be confusing & risk losing edits to source, if it's not crystal clear that the items & the rest need to be separately updated. [EDIT: perhaps could modify 'change source' window so it updates everything on source except items; and add new 'change source items' window - accessed via modified action from 'items' button on source admin to open this new window instead - and use this window to change only 'source items' and nothing else on source. Would this reduce the workload and so avoid the bad gateway 'overload'?]
 - address the '502 Bad gateway' problem directly, but that is (probably) about how much work the server has to do how quickly to apply updates - e.g. I've found trying to change 30-35+ items on 'item list' in one go = bad gateway. With things like item list it's relatively easy to do it in smaller 'chunks': but big sources don't sub-divide, it just looks as if there's too much work for the server ?comparing old & new & figuring out what's changed.

Sorry - both options look like quite significant change...! But perhaps splitting 'change source' sidesteps the main roadblock?

David

**Comment by ahankinson** [comment]
I've increased the timeout to fix the 502s. -- give it a shot and let me know if there are any improvements.

If you can send a link to a problem record that would be helpful for diagnosing any problems or improvements.

**Comment by ahankinson** [comment]
This seems to be fixed now. Closing.
