### ISSUE TITLE
bibliography formatting glitch

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#466]
There is some trailing punctuation appearing in bibliography entry 7282, though everything in the editing fields seems to be as it should be.
![Screen Shot 2019-09-30 at 17 30 30](https://user-images.githubusercontent.com/10816169/65897832-1a7e3380-e3a8-11e9-8548-9fff2e8b0248.png)

**Comment by ahankinson** [comment]
A journal article needs the pages after the volume number. I've updated the record with the pages, so this should appear on the next reindex.
