### ISSUE TITLE
Bristol and parent countries

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#468]
Is apparently showing up as a country, although it is listed as a city with a country parent. It is also listed as a town under United Kingdom. It's the only town that country has. I would prefer England, Scotland, Wales and N Ireland be united under United Kingdom, as in other usage. England, Wales etc are only relevant as provenance areas.
<img width="479" alt="Screen Shot 2019-10-14 at 16 18 51" src="https://user-images.githubusercontent.com/10816169/66763556-f5a5b800-ee9f-11e9-890c-36a9ac33a260.png">

**Comment by juliacmcf** [comment]
Cities seem to have been separated out in migration by mistake.

**Comment by ahankinson** [comment]
I think the problems with the country list are now fixed.
