### ISSUE TITLE
Display item information with image scroll

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#47]
The information about what is on each page is now transferred in the IIIF manifest as a 'structures' block. Inside of this block there is a range that gives the "canvases" (== pages) that a specific composition appears on in that source.

As a user scrolls, the information should appear on the blank space to the left of the image viewer. (See the Cantus Ultimus viewer for a model of how this should work.)

This could be implemented as a Diva plugin so that we can listen to the Diva page changing events.

**Comment by belljustin** [comment]
These are the things I plan to include in the image viewer, unless directed otherwise:
- Service label
- Composer
- Folio, start and end date
- Voices
 - label
 - type (if specified)
 - language
- Composition (Which is waiting on #70)

I'm still very undecided on styling and ordering of this content

**Comment by ahankinson** [comment]
Sounds good. I've merged #70. 

Are you talking about displaying this information, or about including this information in the service output?

**Comment by belljustin** [comment]
displaying the information

**Comment by belljustin** [comment]
@ahankinson I'm having trouble figuring out how to make this look pretty
![screen shot 2016-06-08 at 3 13 23 pm](https://cloud.githubusercontent.com/assets/8331769/15907646/0a7eaf12-2d8c-11e6-8401-2f0896f8c7e4.png)

**Comment by belljustin** [comment]
TODOs:
- [ ] Main heading should read _Folio: {page name}_
- [ ] include folio range in brackets next to composition title
- [ ] change `<ul>` to `<p>`
- [ ] Voice type should be explicit even if it's _no designation_

**Comment by belljustin** [comment]
- [ ] give image-item-listing div fixed height and hide overflow
- [ ] bold the tags
- [ ] toggle voices visibility

**Comment by belljustin** [comment]
Not sure how to style the voices dropdown. If I bold the tags, it looks like a bit much. It might be nice to arrange the info in cols (i.e. a table) but I'm afraid it would just promote a bunch of ugly text wrapping.
- [ ] figure out styling for voices dropdown
- [ ] convert `ul`s to tables?
![screen shot 2016-06-09 at 12 27 23 pm](https://cloud.githubusercontent.com/assets/8331769/15937608/96c43846-2e3d-11e6-9db5-9052170edeca.png)
