### ISSUE TITLE
Source for short description?

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#474]
When searching for e.423, the short description of the MS in the search results states that there are '15 composers inventoried. Contains 124 pieces.'

However, when clicking on the MS and locking at the full record, the description reads under Contents reads '128 pieces from 10 composers.'

Where is is picking these two up from?

**Comment by ahankinson** [comment]
They are calculated slightly differently, depending on the number of uninventoried or blank sections, anonymous composers, or items that have an 'attribution' but no composition attached. I've made the section in the source description a bit clearer; it now reads:

"128 pieces from 10 composers. Contains 1 uninventoried works or miscellaneous sections."
