### ISSUE TITLE
Search Results for country (fail)

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#475]
I put 'Australia' into the search box as I couldn't remember the name of the archive with a new fragment, but it didn't come up (Caboolture). The archive is correctly attached to the country, and it comes up if I type AUS instead (as does a whole load of other stuff that has nothing to do with Australia - using the full name was an attempt to pre-filter). So searching on Australia does not find the Caboolture source or archive, even though I put it up over a month ago. A bug?

**Comment by ahankinson** [comment]
I've put in a fix for this. It should make it into the next reindex. (happening now)
