### ISSUE TITLE
browse by country broken

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#478]
The list produced by the 'browse by country' dropdown on the main menus is completely haywire. Cities are classified as countries, and if I click on them I get a 404 error.

I think I raised this before but can't find it. The countries are correctly linked to parent countries (i.e. UK) as far as I can tell. I think it only affects cities that are children of the UK.

**Comment by ahankinson** [comment]
Fixed in 64eb4740e175ebbd92c9fdeedb828cc70ddceb7f
