### ISSUE TITLE
user groups settings

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#492]
Could there be a checkbox in the user group definition that would include members of that group in the email notifications of problem reports? At the moment only those in the 'Editor' group receive notifications of problem reports, but with new editors I would like them to receive problem reports without full editor status, so they can do some fixes to get used to the system on an add/edit only basis before we give them full delete privileges.

**Comment by ahankinson** [comment]
No checkbox availability (the Groups form is built-in) but I can add the "Add-edit only" group to the e-mail notification list, so these members should start receiving the e-mails.
