### ISSUE TITLE
Sort order (numbering) fields

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#548]
Is there any way the sort order field in items (inventories) and pages could be set to accept decimal numbers (e.g. 47.1, 47.2, 47.3 etc.)?

If we have to insert a piece/page into an inventory/MS, we usually end up having to renumber everything after the insertion, which is a bit of a nightmare as quite often the system breaks when you try to save a renumbered series unless you save every few edits.

**Comment by ahankinson** [comment]
Did you try non-decimal (471, 472) values?

I think it sorts asciibetically, so I think it sorts 1, 10, 100, 2, 20, 200, etc.

**Comment by ahankinson** [comment]
Fixed now.
