### ISSUE TITLE
Merge geographical areas broken

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#549]
502 Bad Gateway when attempting to merge 2 records:
Bartfa and Bártfa (= Bartfeld = Bardejov)

**Comment by ahankinson** [comment]
Are they particularly large records with a lot of attachments?

**Comment by juliacmcf** [comment]
I don't think so -- but Bartfa has 67 MSS attached to it, and apparently so has 'Bartfeld', and they are the same MSS.

**Comment by ahankinson** [comment]
I just successfully merged them and deleted the record for `Bártfa (= Bartfeld = Bardejov)`

**Comment by ahankinson** [comment]
( I didn't do anything special -- gremlins?)

**Comment by juliacmcf** [comment]
Yeah, maybe. I tried a couple of times, BUT I was doing it without keeping the original record, so maybe it didn’t like that?

**Comment by ahankinson** [comment]
Oh, maybe. I did it in two steps.
