### ISSUE TITLE
Integrate provenance information for geographic regions

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#59]
The data is in Solr, just need to use it now.

**Comment by belljustin** [comment]
What's left for this?

**Comment by ahankinson** [comment]
There are two ways to do this:

1. Create a multi-valued array of all the `GeographicArea` records that are present on a source when indexing that source. When a city record is retrieved (https://beta.diamm.ac.uk/cities/246/) we can then do a Solr query for, e.g., `type:source geographic_area_ii:246` to retrieve all the sources that are related to that area.

2. Use the source provenance records to do a query for a particular type of record. If the GeographicArea record is a city, then the solr query would be `type:sourceprovenance city_i:246`; if it was a country record it would be `type:sourceprovenance country_i:XXX`. 

No. 1 requires some additional information added to the source records (through the Source Search Serializer) but it would be pretty quick after that (it puts the slowness at index-time, rather than retrieval time.) No. 2 can be done without any indexing changes, but would require an extra Solr call for each sourceprovenance record retrieved.

**Comment by ahankinson** [comment]
Actually, there is also a third way: Index all geographic areas in Solr (they're not indexed now) and dump the source information for them there. You could probably do that with a `_childDocuments_` index (see https://github.com/diamm/diamm/blob/master/diamm/serializers/search/page.py#L55 for the index serializer and https://github.com/diamm/diamm/blob/master/diamm/serializers/iiif/manifest.py#L124 for an example query on `_childDocuments_`

I think I would still go with No. 1, but the advantage of No. 3 is that you can embed as much (or as little) source information in the child documents as possible.

**Comment by ahankinson** [comment]
Done.
