### ISSUE TITLE
Trouble loading images (Chicago 645)

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#590]
https://www.diamm.ac.uk/sources/634/#/images
I've been trying to get these images online as they were marked as private, but should have been public. The images aren't showing up in the image records or on the live site. The records were all there and the images already uploaded, so all I've done is change from private to public. I've stared at the folder and filenames for ages, but can't see what might be wrong: I've re-fetched the IIIF data a few times and also re-input the file and folder names using cut and paste to make sure it matches what is on the server, but still no dice. 

What am I missing, or is this just a matter of waiting for a re-index?
Julia

**Comment by ahankinson** [comment]
I've just started a reindex -- let's see if that clears it up.

**Comment by juliacmcf** [comment]
Thank you.

**Comment by ahankinson** [comment]
The images are now showing up for me. If it's fixed could you please close this issue?
