### ISSUE TITLE
item missing on Resources menu (live site cms)

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#593]
for some reason the DIAMM Publications Open Access Texts page is not showing up on the Resources menu, even thogh as far as I know the page was created correctly and is in the list. I've just tried shuffling the menu order but that didn't help either. See screenshot. I've labelled this as a 'bug', but it's in Wagtail rather than your code, unless I've just done something stupid when I created the page.
<img width="945" alt="Screen Shot 2024-08-28 at 16 31 33" src="https://github.com/user-attachments/assets/4c9084cc-4ccb-4897-8eae-0d65e32d156d">

**Comment by ahankinson** [comment]
It's a bit hidden, but if you go to the "promote" tab at the top, you'll find a checkbox that says "Show in menus" -- check that, and then publish the page and it should work!

![image](https://github.com/user-attachments/assets/01cf7fb5-8020-4369-b25a-dc6ee558ada8)
