### ISSUE TITLE
Search Facets, Filters, and Sorts

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#6]
Facet/Filter by:
- Type (source, composition, etc.)
- Date (for those items where this matters)

Sort by:
- Name (how? give every object a 'name' field?
- Date

**Comment by belljustin** [comment]
Would we be interested in a facet that filters search results by century?

**Comment by ahankinson** [comment]
Yes. Can you throw out some ideas for how you would implement it?

**Comment by belljustin** [comment]
Sources are indexed with start and end dates. We could have century filters that include sources where the chosen century is included in [start_date, end_date)

**Comment by ahankinson** [comment]
Done.
