### ISSUE TITLE
Many bibliography entries have duplicate names

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#63]
This comes from trying to reconcile multiple places for names in the database. Will have to investigate to know if it's from Filemaker, or from the bibliography import process (I suspect the latter).

**Comment by juliacmcf** [comment]
If this refers to the abbreviation for each bibl. entry then I have checked and there are none in the bibliography table. However there will be MANY in the Bibliography-Source intersection set (BibliographySource_IS). Could the two have become confused during import?

**Comment by ahankinson** [comment]
"Names" in this case is authors. For example: 

Gallo, Franco Alberto, and F. Alberto GALLO. 1977. Il Medioevo. 2 vols. Turin: Edizioni di Torino. pp. 78, Readings 5.2.

I think we spoke about this earlier -- there are two places that authors are listed in the bibliography table -- one in the table, and one in the authors table. You said that you think all the authors in the bibliography table are also in the authors table, but I haven't had any opportunity to check and see if this is true. 

So this note was more a reminder to me to investigate this.

**Comment by juliacmcf** [comment]
Ah yes. I remember. They should just be straight duplicates: I have to have the name in the Bibliography table to enable me to ‘calculate’ the bibliography display. You won’t need those fields so could ignore them in your upload/download, and use only data from the author table, which should be more complete than that info in the bibliog table (where I ran out of fields in multi-author or multi-editor books).
