### ISSUE TITLE
Old catalogue descriptions

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#64]
By the end of this website development we should have newly formatted and in some cases entirely newly written source descriptions to complement the stunning new interface. However the RISM and Census Catalogue descriptions have historical (and historiographical) importance and should not be lost. However I'd prefer not to have them appear on the same page as the new description, just have them accessible. New description, RISM and Census are all at the moment in separate fields in the database, but collated into a big 'description' field for upload to the live site. This means it should be easy to separate them out. I can for instance retain the old catalogue descriptions in the 'description' field where we haven't got a new description, but drop them to a secondary field if we have. Looking at the way the current website functions, I would want to put the old catalogue descriptions either behind a single tab, or behind dedicated ones each for RISM and Census. (or whatever you would do with them). Can this be achieved? I'd definitely like to divorce the old catalogue descriptions from the new description.

**Comment by ahankinson** [comment]
Yes.

At the moment, RISM and CCM descriptions have their own type (see: https://github.com/diamm/diamm/blob/master/diamm/models/data/source_note.py#L25)

These are maintained as separate fields on the new database interface, and drawn dynamically to the record on request. (They are not actually collated together and stored in the database). They can go anywhere you like. We could have a separate tab sections for 'historical descriptions' or whatever you like.

**Comment by ahankinson** [comment]
RISM and CCM descriptions are now filed at the bottom of the 'description' page.
