### ISSUE TITLE
Zero heights in manifest cause diva failure

### ISSUE THREAD

**Issue by belljustin** [diamm/diamm#75]
The source with pk:1236 links to a manifest with zero height canvases. This causes a range error in diva and the images are unable to load

**Comment by ahankinson** [comment]
@juliacmcf -- I looked into it, and some image files for D-Ju Chb 36 (sourceKey 1236) have `.tif` appended to them, which is breaking the site. If you remove .tif from these, it will fix the issue.

Also some for A-Wn Cod. 4809 (sourceKey 2065) and one for A-Wn Cod. 11883 (sourcekey 1985). These should be fixed as well.

**Comment by juliacmcf** [comment]
These are fixed in the filemaker database

**Comment by ahankinson** [comment]
Great, thanks!
