### ISSUE TITLE
Integrate news stories on front page

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#76]
News articles should appear on the front page. 

`Story` models are already written.

https://github.com/diamm/diamm/blob/master/diamm/models/site/story.py

**Comment by belljustin** [comment]
Looks like you resolved this one with 2ee4611f, @ahankinson. I'll close it

**Comment by ahankinson** [comment]
Nah, I really meant clean up the 'lorem ipsum' and add a few real stories to the front page.

https://github.com/diamm/diamm/blob/master/diamm/templates/index.jinja2

**Comment by ahankinson** [comment]
Fixed.
