### ISSUE TITLE
GB-Ob Can. Misc 213 Image 081

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#81]
The database lists the filename for image 81 correctly as `GB-Ob_CanMisc213_081`, but this image doesn't exist on the server. Instead, there are two files:

GB-Ob_CanMisc213_081 1.jp2
GB-Ob_CanMisc213_081_1.jp2

I've copied `GB-Ob_CanMisc213_081 1.jp2` to `GB-Ob_CanMisc213_081.jp2` to fix it, but this should probably be fixed in the DIAMM image file system.

**Comment by juliacmcf** [comment]
I've used GB-Ob_CanMisc213_081_1 (with the underscore) since we're trying to avoid anything with spaces in the filenames.
