### ISSUE TITLE
Update images for GB-Lbl Add. MS 5465 (Fayrfax MS)

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#84]
They look awful!

https://www.diamm.ac.uk/sources/1237/

![image](https://cloud.githubusercontent.com/assets/163183/15987873/84d4fae0-3008-11e6-81ae-032b6f01928c.png)

**Comment by juliacmcf** [comment]
There are probably a LOT like this. We did a huge upload/replace of images, and DDH set the jp2 to compress massively. I complained and they changed the setting, but did *not* reprocess the files.

**Comment by ahankinson** [comment]
Right now I think the plan is to re-do all of them... I just posted this because I thought it was especially bad, and a good candidate for updating.

**Comment by ahankinson** [comment]
Will be solved since we're re-encoding everything.
