### ISSUE TITLE
Broken record

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#86]
https://beta.diamm.ac.uk/sources/670/

`'NoneType' object is not subscriptable`

Looks to be a problem with cover images.

**Comment by mscuthbert** [comment]
Not sure if it's related, but https://beta.diamm.ac.uk/sources/253/ has difficulties too.

(WOW, super impressed w/ everything!)

**Comment by ahankinson** [comment]
Thanks Myke, I'll make a new issue for this one and track it there.

The particular issue w/ sources/670 was fixed in the latest update (today).

**Comment by ahankinson** [comment]
Fixed.
