### ISSUE TITLE
Archive alternative names

### ISSUE THREAD

**Issue by mscuthbert** [diamm/diamm#89]
In addition to former names, 

Is there a field for alternative names for archives?  For instance:

https://beta.diamm.ac.uk/archives/172/  -- home of https://beta.diamm.ac.uk/sources/7/
is also "Cathédrale Notre-Dame" and also "Bibliothèque capitulaire" and also “Bibliothèque de l’Eglise Cathédrale de Tournai”,  -- all names that have appeared in the literature  (Julia aside -- source 7 is now MS A 27; and before 476 had an olim of MS Voisin IV)

This archive has both names in the title:
https://beta.diamm.ac.uk/archives/126/ 
we should choose the one they use which is "Biblioteca de Catalunya"  -- they seem to have backed down from the politically provocative Biblioteca Nacional de Catalunya used before.

Many of the alternative names are due to language differences -- perhaps that would be important eventually to capture.  Again, Catalan sources are among the most difficult for these because nationalistic ideas leave both Spanish and Catalan names in common use.

Thanks!

**Comment by ahankinson** [comment]
There is provision for archive notes. We could make a note type for "Other names" which would appear on the record.

**Comment by mscuthbert** [comment]
I think that that would work great. If this were fully OOP I would make all of these names be subclasses of an ArchiveName class that could be pretty specific about what the role of the name is, but my sense is that with Django this would be more difficult than it would be advantageous?

**Comment by ahankinson** [comment]
A Django model is equivalent to a row in a database, so it makes more sense to make it a property on a model since that translates to a column in a RDBMS. In most cases I make these enumerated types so that I can then refer to their type in code as, e.g., ArchiveNote.FORMER_NAME or Source.PARCHMENT.

e.g., https://github.com/diamm/diamm/blob/master/diamm/models/data/source.py#L19

**Comment by mscuthbert** [comment]
Very cool.  I like, I like.  (and I also like not going overboard and making each of the enumerated types be its own table with foreign keys, etc.)

**Comment by ahankinson** [comment]
@belljustin could you please add an "Other Names" type to archive notes?
