### ISSUE TITLE
Change default for no Inventory from "Since this source is post-1550"

### ISSUE THREAD

**Issue by mscuthbert** [diamm/diamm#91]
There are many sources that have the inventory mention:
"Since this source is post-1550, a complete inventory has not been supplied."
but are not post-1550.  For instance

https://beta.diamm.ac.uk/sources/4061/
https://beta.diamm.ac.uk/sources/4069/
https://beta.diamm.ac.uk/sources/3939/
etc.

It seems to me that the placeholder message for "No Inventory" should be more generic.  "No inventory available." And then only if some other tick marks it as a post-1550 source should the longer message appear.

Btw -- this source which has the message -- https://beta.diamm.ac.uk/sources/651/ -- should be deleted.  It is in fact a duplicate of https://beta.diamm.ac.uk/sources/723/

**Comment by juliacmcf** [comment]
I have fixed the 'no inventory' message. I have deleted source 651 but could I check which library is the correct one? These have different library names in Perugia, and I don't want to lose the wrong one. I should delete a library that also has nothing in it.

**Comment by ahankinson** [comment]
What did you change it to? I don't use the message the comes out of Filemaker -- it's automatically added to a record when it is viewed, but it means I have to update it in the software.

**Comment by juliacmcf** [comment]
Sorry — the item now reads: "This MS has not yet been inventoried by DIAMM. If you would like to submit an inventory, please send it to diamm@music.ox.ac.uk”. All of these records are linked to compositionKey 79920, which has the same ‘title’. Might be better to make the change via the compositionKey rather than the text? If you’re already fixing it, it won’t be important of course, this is just for what will show on the old site. I’d prefer to delete all of these records, but they were put in as Elliott’s script broke if a source had no items attached.

**Comment by ahankinson** [comment]
I've already fixed it, I think. 79920 is one of the records I skip when I migrate the data to the new system. Now, sources don't have to have items, items don't have to have compositions ("Works by Mr. Smith" records), and compositions don't have to have composers (anonymous compositions).

**Comment by mscuthbert** [comment]
@juliacmcf -- following up on a question mentioned here (that does not affect the closed status of this issue, but might possible open another one): The library name/situation for the Source https://beta.diamm.ac.uk/sources/723/ -- is complex and comes down to "what's the line between a library and a shelfmark?"

To the best of my understanding, the book still belongs to the Biblioteca Universitaria of Perugia, as shelfmark Incunabolo inv. 15755 N.F.  -- however, a small portion of the books in that library are stored in the anteroom of the University rector's office, which they call the Biblioteca del Dottorato.  I don't think that there's a separate administrative structure for this collection, so normally, we would call it the Biblioteca Universitaria, but I think that calling it Biblioteca del Dottorato is the right thing to do, since our job is to help scholars, not be technically correct, and using this name tells someone you're going to need to contact the Rector's office to gain access, and the hours will be limited to those when the rector is not using his office/meeting guests, but when the associate/assistant is around.  Saying that it's a shelfmark in the Biblioteca Universitaria will not prepare our users for these negotiations.

Btw -- they have also given it another shelfmark for as long as it is in this space.  It is "Cas. 3" as seen on  http://raritamusicali.unipg.it/galleria.php?concerto=3

**Comment by juliacmcf** [comment]
Lord, that’s complicated. 

If I put Biblioteca del Doctorate (as if a separate library) users may not realise that this is within the BU (I don’t know what RISM does…). Might be better to make a new library which is "BU: B d D”? We can put a note on the MS description about contacting the rector’s office to gain access.

The additional shelf mark should really appear in the shelf mark field…

**Comment by ahankinson** [comment]
I think 'Biblioteca del Dottorato' is technically a collection within the library (the word 'Biblioteca' is probably confusing matters). Could we just mention somewhere that's where it is?

**Comment by mscuthbert** [comment]
I think that the closest analogy would be with how to handle manuscripts owned by one library but on deposit with another.  [Machaut Vg?  Definitely https://beta.diamm.ac.uk/sources/232/ ] -- I think that where the manuscript is housed is the most important part of the shelfmark, and the owner (who may need to be contacted for rights permissions) is secondary for research purposes.  The Biblioteca del Dottorato isn't a part of the Biblioteca Universitarià even though the BU keeps some of their books there.  When I asked around at the BU no one had even heard of the library.  That suggests that sending people to the BU first is not the best direction.

The Source 232 [lnked above] is another case where yes the Biblioteca Comunale technically owns the manuscript but all questions about the manuscript and all access questions need to go to the Sacro Convento.

These may seem like little nitpicky details, but both of these manuscripts caused problems for me ranging from needing to come back a week later to needing to come back two months later, neither of which I knew about until I went to the library which was cited in the literature (and DIAMM), which I had already contacted about their access privileges and opening hours, but turned out was not the right library.    Accurate information about the name, shelfmark, and call number of MSS is probably DIAMM's second most important mission (after photography and image preservation/dissemination) and to me is more important than inventories, bibliography, etc.  Thanks!

**Comment by juliacmcf** [comment]
At the moment I'm putting problems like this (or rather their solutions) into the notes, but those don't necessarily appear foregrounded. We could easily put this sort of information at the top of the MS description; although people are coming to DIAMM for information about sources, information about how to see the real object is pretty crucial, so I think worth foregrounding in this way where we know there is an issue. I don't want to move the 'notes' field to the top of the description as it's normally used just to deal with 'other information' that would normally not be important in the same way.

**Comment by ahankinson** [comment]
I wholeheartedly agree! I'm just wondering if it requires a schematic structure change, or if it is information best captured in a notes field.

My 'spidey sense' tells me that there is a greater possibility of cascading effects on all sources if we somehow special-case these instances and formalize the special cases into the schema. These cascading effects could range from hard-to-catch semantic errors in the data display (improperly / incomplete display of search results) to non-specialized cataloguing practices (i.e., a human puts a bit of information in a wrong field). 

On the other hand, there is an 'Ownership note' type already present on sources. (See: https://github.com/diamm/diamm/blob/master/diamm/models/data/source_note.py#L15) 

I guess what I'm saying is that I'm not sure dealing with these necessarily requires a schema change, and we may already be able to deal with this particular case -- it's just a matter of deciding on the appropriate cataloguing practice from a DIAMM staff side.

**Comment by mscuthbert** [comment]
My "staff side" feeling :-) is that the key entry for any source is where is it.  This is why the shelfmark I use for https://beta.diamm.ac.uk/sources/226/ in my pubs is not "manuscript without shelfmark" or "s.s." but "MS without shelfmark, in a light-gray binder currently on the same shelf as Lat. 219 and 224" -- anyone who has ever gone to a library and asked "Can you get me your manuscript without call number" will understand.  Catalogers who haven't worked outside their libraries won't. 

I think that it goes to what was my main worry (but hasn't really arisen thank goodness!) about emphasizing Muscat / RISM for DIAMM: their main audience is librarians, ours is researchers.  I'll always err on the side of practicality over technical correctness in terms of what gets foregrounded and what appears in a note below.

Do we possibly need a priority level enum attached to the note types?

**Comment by juliacmcf** [comment]
Yes, at the moment the notes are just 'notes', if we could indicate priority I think that would solve this problem. I remember the MS in the light gray binder. That info went into the notes. Technically I feel we have to put what the library puts in terms of shelf marks, but agree that 'without shelf mark' is singularly useless in any context, and in these cases we should at least supplement that information in another field, if not in the shelfmark field.

**Comment by ahankinson** [comment]
I'm well aware of that possibility, and actively trying to abstract out the libraryness from the front-end. :) 

However, the challenge is that the "libraryness" does serve a role in a) keeping things nice and orderly so that they can be easily interoperable / understood, and b) helps build on a set of formal rules for source description such that we don't need to reinvent wheels. 

I do have a problem with 'priority' though -- what does it mean? Is it a notes sort order (priority 1 is listed at the top)? Or is it a flag that makes a bit of information appear in a place it wouldn't otherwise? In the context of this conversation it's fairly obvious, but would 'priority' on a note field make sense otherwise?

I think a better method is to use the facilities in the 'Source Identifier' model: 

https://github.com/diamm/diamm/blob/master/diamm/models/data/source_identifier.py

We could create a type of 'Other' (or a more specific term, like 'Collection' or something -- I don't particularly like miscellaneous types...). Sources can have multiple identifiers. 

The 'identifier' field itself is restricted to 255 characters, since anything beyond that is not really an identifier, but an identifier with some extra qualifying information. There is a 'note' field on identifier that could be used for further information. 

So a `SourceIdentifier` entry for `sources/723` might be:

```
type: collection
identifier: Cas. 3
note: Held in the anteroom of the University rector's office, referred to as Biblioteca del Dottorato. Access restricted to room availability. Contact the Rector's office to gain access.
```

How does that sound?
