### ISSUE TITLE
Vallière search: Duc and Duke don't work.

### ISSUE THREAD

**Issue by mscuthbert** [diamm/diamm#92]
Symptom: do a search for "Vallière".

You will find "Duc de la Vallière" and "Duke of La Valliere" -- these are presumably the same Person, so that'd just be a database error to fix later.  However, clicking either of them gives an error message which includes a KeyError on public_images_b  in the get_related_sources() call of person.py.  Possibly there is a solr_relationships entry for Person objects that no longer should be there?

**Comment by ahankinson** [comment]
Actually, I will close this -- duplicated (but slightly different) names for database entities are present throughout, so there's no point in keeping this one open since it will hopefully be addressed later.

The exception, however, is now fixed.

**Comment by mscuthbert** [comment]
Thanks! It was the exception that was important to me. I wasn't sure if the similar names were at fault.
