### ISSUE TITLE
Incorrectly displayed thumbnail

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#93]
For some reason this record is showing a (broken) thumbnail but it doesn't have any images attached. 

https://www.diamm.ac.uk/sources/723/

**Comment by mscuthbert** [comment]
Looks good now.  :-)

**Comment by mscuthbert** [comment]
spoke too soon -- it looks like about 1 in 3 times it is correct and the other 2 in 3 it gives a broken thumbnail, depending on which page it is randomly choosing.

**Comment by ahankinson** [comment]
@belljustin could you investigate this bug and report back on what you found (before fixing it)?

**Comment by belljustin** [comment]
I can't seem to reproduce this bug

**Comment by ahankinson** [comment]
Fixed.
