### ISSUE TITLE
Bug: Indexing failure for organizations

### ISSUE THREAD

**Issue by ariellegoldman** [diamm/diamm#95]
When organizations are reindexed an attribute error appears:
AttributeError: 'NoneType' object has no attribute 'name'

Traceback:
```  File "/Users/ariellegoldman/Documents/code/diamm/env/lib/python3.5/site-packages/serpy/serializer.py", line 109, in _serialize
    result = getter(instance)```

**Comment by ahankinson** [comment]
Did you pull the latest changes? I think this was fixed in 77f8a6af696c0076b5372da4103d1171f7bf0fc5

**Comment by ariellegoldman** [comment]
I pulled the changes but it still seems to be broken for me. It works when I replace 'location.name' with 'name' in the search serializer
